/**
 * iconForType — maps a stored link `type` string to a Lucide icon component
 * and its brand glyph color (via CSS variable).
 *
 * Source of truth: src/lib/pbLinkIcons.generated.ts (generated by PB
 * gen_links.py from link_contract.py). Never import PB_LINK_ICONS[type].color
 * directly for rendering — always go through the CSS token so dark-mode
 * overrides (e.g. GitHub near-black → light) apply automatically.
 *
 * Fallback: unknown or missing types → 'web' (Globe, slate).
 */

import {
  FileText,
  Sheet,
  Presentation,
  ClipboardList,
  Box,
  FolderGit2,
  CircleDot,
  GitBranch,
  Mail,
  PencilLine,
  BookText,
  FolderOpen,
  File,
  FileCode,
  Globe,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import { ICONS_HASH } from './pbLinkIcons.generated'

export { ICONS_HASH }

export interface LinkIconSpec {
  Icon: LucideIcon
  color: string  // CSS variable reference, e.g. 'var(--link-google-doc)'
}

// Explicit named-import map: 15 types from PB_LINK_ICONS.
// Keys MUST match PbLinkType exactly (from pbLinks.generated.ts PB_LINK_TYPES).
const ICON_MAP: Record<string, LinkIconSpec> = {
  google_doc:    { Icon: FileText,      color: 'var(--link-google-doc)' },
  google_sheet:  { Icon: Sheet,         color: 'var(--link-google-sheet)' },
  google_slide:  { Icon: Presentation,  color: 'var(--link-google-slide)' },
  google_form:   { Icon: ClipboardList, color: 'var(--link-google-form)' },
  box_folder:    { Icon: Box,           color: 'var(--link-box-folder)' },
  github_repo:   { Icon: FolderGit2,   color: 'var(--link-github-repo)' },
  github_issue:  { Icon: CircleDot,    color: 'var(--link-github-issue)' },
  github_tree:   { Icon: GitBranch,    color: 'var(--link-github-tree)' },
  gmail_thread:  { Icon: Mail,         color: 'var(--link-gmail-thread)' },
  gmail_draft:   { Icon: PencilLine,   color: 'var(--link-gmail-draft)' },
  obsidian_note: { Icon: BookText,     color: 'var(--link-obsidian-note)' },
  local_folder:  { Icon: FolderOpen,   color: 'var(--link-local-folder)' },
  local_file:    { Icon: File,         color: 'var(--link-local-file)' },
  script:        { Icon: FileCode,     color: 'var(--link-script)' },
  web:           { Icon: Globe,        color: 'var(--link-web)' },
}

const FALLBACK: LinkIconSpec = ICON_MAP.web

/**
 * Returns the Lucide icon component and CSS-variable color for a stored link
 * type string. Unknown/missing types fall back to the 'web' entry (Globe,
 * slate).
 */
export function iconForType(type: string | null | undefined): LinkIconSpec {
  if (!type) return FALLBACK
  return ICON_MAP[type] ?? FALLBACK
}
