/**
 * iconForType — maps a stored link `type` string to a Lucide icon component
 * and its brand glyph color (via CSS variable).
 *
 * Source of truth: src/lib/pbLinkIcons.generated.ts (generated by PB
 * gen_links.py from link_contract.py). ICON_MAP is now DERIVED from
 * PB_LINK_ICONS — no parallel hand-maintained list. Adding a new link type
 * in PB auto-cascades to the Hub icon map once gen_links.py is rerun.
 *
 * Color: always a CSS variable reference (e.g. 'var(--link-google-doc)') —
 * never the raw hex from PB_LINK_ICONS[type].color — so dark-mode overrides
 * (e.g. GitHub near-black → light) apply automatically via index.css .dark.
 *
 * Fallback: unknown or missing types → 'web' (Globe, slate).
 */

import {
  FileText,
  Sheet,
  Presentation,
  ClipboardList,
  Box,
  FolderGit2,
  CircleDot,
  GitBranch,
  Mail,
  PencilLine,
  FilePen,
  BookText,
  FolderOpen,
  File,
  Globe,
  Sparkles,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import { PB_LINK_ICONS, ICONS_HASH } from './pbLinkIcons.generated'

export { ICONS_HASH }

export interface LinkIconSpec {
  Icon: LucideIcon
  color: string  // CSS variable reference, e.g. 'var(--link-google-doc)'
}

/**
 * Lucide component registry — maps the displayName string from PB_LINK_ICONS
 * to the imported Lucide component. Must be kept in sync with the 16 types
 * in link_contract.py LINK_TYPE_ICONS. The parity test
 * (src/lib/__tests__/iconMapParity.test.ts) asserts every PB_LINK_ICONS entry
 * has a matching key here.
 */
const LUCIDE_REGISTRY: Record<string, LucideIcon> = {
  FileText,
  Sheet,
  Presentation,
  ClipboardList,
  Box,
  FolderGit2,
  CircleDot,
  GitBranch,
  Mail,
  PencilLine,
  FilePen,
  BookText,
  FolderOpen,
  File,
  Globe,
  Sparkles,
}

/**
 * Converts a PB link type key (e.g. 'google_doc') to the CSS variable name
 * (e.g. '--link-google-doc'). Underscores → hyphens.
 */
export function cssTokenForType(type: string): string {
  return `--link-${type.replace(/_/g, '-')}`
}

/**
 * ICON_MAP is derived from PB_LINK_ICONS so that any gen_links.py regeneration
 * automatically updates the Hub icon map — no hand-maintenance.
 *
 * If PB_LINK_ICONS includes a lucide name not yet imported above, the entry
 * falls back to Globe at runtime and the parity test will catch the gap.
 */
const ICON_MAP: Record<string, LinkIconSpec> = Object.fromEntries(
  Object.entries(PB_LINK_ICONS).map(([type, spec]) => {
    const Icon = LUCIDE_REGISTRY[spec.lucide] ?? Globe
    const token = cssTokenForType(type)
    return [type, { Icon, color: `var(${token})` }]
  })
)

const FALLBACK: LinkIconSpec = ICON_MAP.web ?? { Icon: Globe, color: 'var(--link-web)' }

/**
 * Returns the Lucide icon component and CSS-variable color for a stored link
 * type string. Unknown/missing types fall back to the 'web' entry (Globe,
 * slate).
 */
export function iconForType(type: string | null | undefined): LinkIconSpec {
  if (!type) return FALLBACK
  return ICON_MAP[type] ?? FALLBACK
}
