// GENERATED by gen_links.py -- do not edit. Link-type render order (#153).
export const DISPLAY_ORDER_HASH = "5515003e1589ae1a576204907233ff124255a990822c1c8627cba71ba0a860de";
export const LINK_TYPE_DISPLAY_ORDER = ["iwd", "google_doc", "google_sheet", "google_slide", "google_form", "obsidian_note", "gmail_thread", "gmail_draft", "box_folder", "github_repo", "github_issue", "github_tree", "local_folder", "local_file", "script", "artifact", "web"] as const;
export const LINK_TYPE_DISPLAY_RANK: Record<string, number> = {
  "artifact": 15,
  "box_folder": 8,
  "github_issue": 10,
  "github_repo": 9,
  "github_tree": 11,
  "gmail_draft": 7,
  "gmail_thread": 6,
  "google_doc": 1,
  "google_form": 4,
  "google_sheet": 2,
  "google_slide": 3,
  "iwd": 0,
  "local_file": 13,
  "local_folder": 12,
  "obsidian_note": 5,
  "script": 14,
  "web": 16
};

// Render rank for a LinkType; unknown/null sorts LAST.
export function displayRank(linkType: string | null | undefined): number {
  return linkType != null && linkType in LINK_TYPE_DISPLAY_RANK
    ? LINK_TYPE_DISPLAY_RANK[linkType]
    : 17;
}
