// GENERATED by gen_links.py -- do not edit.
export const ICONS_HASH = "ff69496c9230775019b163d7b1cb79d0d87e02c8232c9b027a481078f6e7b2f8";
export type PbLinkIcon = { lucide: string; color: string; colorDark?: string };
export const PB_LINK_ICONS: Record<string, PbLinkIcon> = {
  "artifact": {
    "color": "#6B5420",
    "colorDark": "#DCB355",
    "lucide": "Sparkles"
  },
  "box_folder": {
    "color": "#0061D5",
    "lucide": "Box"
  },
  "github_issue": {
    "color": "#1F2328",
    "colorDark": "#E6EDF3",
    "lucide": "CircleDot"
  },
  "github_repo": {
    "color": "#1F2328",
    "colorDark": "#E6EDF3",
    "lucide": "FolderGit2"
  },
  "github_tree": {
    "color": "#1F2328",
    "colorDark": "#E6EDF3",
    "lucide": "GitBranch"
  },
  "gmail_draft": {
    "color": "#EA4335",
    "lucide": "PencilLine"
  },
  "gmail_thread": {
    "color": "#EA4335",
    "lucide": "Mail"
  },
  "google_doc": {
    "color": "#1A73E8",
    "lucide": "FileText"
  },
  "google_form": {
    "color": "#673AB7",
    "lucide": "ClipboardList"
  },
  "google_sheet": {
    "color": "#188038",
    "lucide": "Sheet"
  },
  "google_slide": {
    "color": "#B26A00",
    "lucide": "Presentation"
  },
  "iwd": {
    "color": "#4F46E5",
    "colorDark": "#A5B4FC",
    "lucide": "FilePen"
  },
  "local_file": {
    "color": "#475569",
    "lucide": "File"
  },
  "local_folder": {
    "color": "#475569",
    "lucide": "FolderOpen"
  },
  "obsidian_note": {
    "color": "#7C3AED",
    "lucide": "BookText"
  },
  "web": {
    "color": "#475569",
    "lucide": "Globe"
  }
} as const;
