// GENERATED by gen_links.py -- do not edit.
export const ICONS_HASH = "5403258cb2ddc522864425d90397b9f8994d95516e3830203b2ce769c43add4d";
export type PbLinkIcon = { lucide: string; color: string; colorDark?: string };
export const PB_LINK_ICONS: Record<string, PbLinkIcon> = {
  "box_folder": {
    "color": "#0061D5",
    "lucide": "Box"
  },
  "github_issue": {
    "color": "#1F2328",
    "colorDark": "#E6EDF3",
    "lucide": "CircleDot"
  },
  "github_repo": {
    "color": "#1F2328",
    "colorDark": "#E6EDF3",
    "lucide": "FolderGit2"
  },
  "github_tree": {
    "color": "#1F2328",
    "colorDark": "#E6EDF3",
    "lucide": "GitBranch"
  },
  "gmail_draft": {
    "color": "#EA4335",
    "lucide": "PencilLine"
  },
  "gmail_thread": {
    "color": "#EA4335",
    "lucide": "Mail"
  },
  "google_doc": {
    "color": "#1A73E8",
    "lucide": "FileText"
  },
  "google_form": {
    "color": "#673AB7",
    "lucide": "ClipboardList"
  },
  "google_sheet": {
    "color": "#188038",
    "lucide": "Sheet"
  },
  "google_slide": {
    "color": "#B26A00",
    "lucide": "Presentation"
  },
  "local_file": {
    "color": "#475569",
    "lucide": "File"
  },
  "local_folder": {
    "color": "#475569",
    "lucide": "FolderOpen"
  },
  "obsidian_note": {
    "color": "#7C3AED",
    "lucide": "BookText"
  },
  "script": {
    "color": "#475569",
    "lucide": "FileCode"
  },
  "web": {
    "color": "#475569",
    "lucide": "Globe"
  }
} as const;
