// GENERATED by gen_links.py -- do not edit. Link-type render order (#153).
export const DISPLAY_ORDER_HASH = "7f721fb07d1c4a852187f8c8beee86d9dca51b2ca5ea095ed7c3b51b4303f903";
export const LINK_TYPE_DISPLAY_ORDER = ["iwd", "google_doc", "google_sheet", "google_slide", "google_form", "artifact", "obsidian_note", "gmail_thread", "gmail_draft", "box_folder", "github_repo", "github_issue", "github_tree", "local_folder", "local_file", "web"] as const;
export const LINK_TYPE_DISPLAY_RANK: Record<string, number> = {
  "artifact": 5,
  "box_folder": 9,
  "github_issue": 11,
  "github_repo": 10,
  "github_tree": 12,
  "gmail_draft": 8,
  "gmail_thread": 7,
  "google_doc": 1,
  "google_form": 4,
  "google_sheet": 2,
  "google_slide": 3,
  "iwd": 0,
  "local_file": 14,
  "local_folder": 13,
  "obsidian_note": 6,
  "web": 15
};

// Render rank for a LinkType; unknown/null sorts LAST.
export function displayRank(linkType: string | null | undefined): number {
  return linkType != null && linkType in LINK_TYPE_DISPLAY_RANK
    ? LINK_TYPE_DISPLAY_RANK[linkType]
    : 16;
}
