// GENERATED by scripts/links/gen_links.py -- DO NOT EDIT BY HAND.
// rules_hash=e0666c37d7f73ce4cc744932f94e86a085dc02c93b2a978e828e149001f88846
// The interpreter lives in shared/pbLinks.generated.ts so the Worker can
// import it too; this path is kept for the frontend importers.
export * from '../../shared/pbLinks.generated'
