name = "hub-realtime"
main = "src/index.ts"
compatibility_date = "2024-09-23"

[durable_objects]
bindings = [
  { name = "NOTIFICATION_HUB", class_name = "NotificationHub" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["NotificationHub"]
