// artifact-link-mirror.test.ts — #196 artifact -> links-table mirror.
//
// The load-bearing invariant is CANONICAL PARITY: the in-api canonical
// (artifactCanonicalUrl) must byte-match what PB's link contract produces, or a
// Hub-created links row and a PB-pushed one won't dedup on the
// (owner,role,canonical_url) partial-UNIQUE. The cross-repo parity test below
// pins it to the generated fixture corpus (the same corpus the pbLinks vitest
// asserts against), so the api/ copy can't silently drift from the contract.

import { describe, it, expect, vi } from 'vitest';
import { artifactCanonicalUrl, mirrorArtifactLink } from './artifact-link-mirror';
import type { Env, AuthUser } from '../helpers';
// api tests may cross the runtime bundle boundary into src/ (precedent:
// api/routes/optimistic-rollback.test.ts). The corpus is generated by PB's
// gen_links.py from the single authored contract.
import fixtures from '../../src/lib/__tests__/link-fixtures.json';

const MOCK_USER: AuthUser = { email: 'ingra107@umn.edu', slug: 'nick-ingraham', isPi: true };

describe('artifactCanonicalUrl — host-normalized canonical', () => {
  it('canonicalizes a prod artifact URL on the stable art_ id', () => {
    expect(artifactCanonicalUrl('https://mn-ccore-lab.pages.dev/portal/artifacts/art_0a1b2c3d')).toBe(
      'https://mn-ccore-lab.pages.dev/portal/artifacts/art_0a1b2c3d',
    );
  });

  it('collapses a non-prod capture origin to the prod canonical (dedup safety)', () => {
    // A staging / preview / custom-domain origin must yield the SAME canonical,
    // else a Hub-created row and a PB-pushed row fork the natural key.
    expect(artifactCanonicalUrl('https://mnccore-lab-test.pages.dev/portal/artifacts/art_0a1b2c3d')).toBe(
      'https://mn-ccore-lab.pages.dev/portal/artifacts/art_0a1b2c3d',
    );
  });

  it('extracts the id from a URL embedded in markdown / trailing punctuation', () => {
    expect(artifactCanonicalUrl('see [the doc](https://mn-ccore-lab.pages.dev/portal/artifacts/art_deadbeef)')).toBe(
      'https://mn-ccore-lab.pages.dev/portal/artifacts/art_deadbeef',
    );
  });

  it('returns null for a URL with no art_<hex> id', () => {
    expect(artifactCanonicalUrl('https://mn-ccore-lab.pages.dev/portal/projects/abc')).toBeNull();
  });
});

describe('cross-repo parity: api canonical == PB contract corpus', () => {
  it('matches the generated artifact fixture canonical_url byte-for-byte', () => {
    const artifactCase = (fixtures as Array<{ raw: string; expected: { type: string; canonical_url: string } }>)
      .find((c) => c.expected.type === 'artifact');
    expect(artifactCase, 'no artifact fixture in the corpus — gen_links.py must emit one').toBeTruthy();
    expect(artifactCanonicalUrl(artifactCase!.raw)).toBe(artifactCase!.expected.canonical_url);
  });
});

// ── mirrorArtifactLink ──────────────────────────────────────────────────────

// Minimal D1 stub covering the 3 query shapes the mirror + applyInsert use:
// (1) the natural-key pre-check, (2) MAX(sort_order), (3) applyInsert's
// INSERT INTO links + readCanonical SELECT * FROM links WHERE id = ?.
function makeStub(opts: { existing?: { id: string } | null; maxSortOrder?: number; throwOnInsert?: boolean } = {}) {
  const { existing = null, maxSortOrder = -1, throwOnInsert = false } = opts;
  const sqlLog: string[] = [];
  let insertedRow: Record<string, unknown> | null = null;

  function stmt(sql: string, vals: unknown[]): any {
    return {
      bind: (...more: unknown[]) => stmt(sql, [...vals, ...more]),
      first: async () => {
        sqlLog.push(sql);
        const u = sql.toUpperCase();
        if (u.includes('CANONICAL_URL = ?') && u.includes("ROLE = 'KEY'")) return existing; // pre-check
        if (u.includes('MAX(SORT_ORDER)')) return { m: maxSortOrder };
        if (u.includes('SELECT * FROM LINKS')) return insertedRow; // readCanonical
        return null;
      },
      run: async () => {
        sqlLog.push(sql);
        if (/^INSERT INTO links/i.test(sql.trim())) {
          if (throwOnInsert) throw new Error('D1_ERROR: simulated insert failure');
          insertedRow = { id: vals[0], seq: 1 };
        }
        return { meta: { changes: 1 } };
      },
    };
  }
  const db = { prepare: (sql: string) => stmt(sql, []) };
  return { env: { DB: db } as unknown as Env, sqlLog, getInserted: () => insertedRow };
}

describe('mirrorArtifactLink', () => {
  const URL_ = 'https://mn-ccore-lab.pages.dev/portal/artifacts/art_abc123';
  const CANON = 'https://mn-ccore-lab.pages.dev/portal/artifacts/art_abc123';

  it('inserts a synced links row for a fresh artifact URL', async () => {
    const { env, sqlLog } = makeStub({ existing: null, maxSortOrder: -1 });
    const res = await mirrorArtifactLink(env, 'tasks', 'task_X', URL_, 'Hermes: Plan', MOCK_USER);
    expect(res).toBe('inserted');
    const insertSql = sqlLog.find((s) => /^INSERT INTO links/i.test(s.trim()));
    expect(insertSql).toBeTruthy();
    // type=artifact + canonical_url must be in the insert column list.
    expect(insertSql).toMatch(/canonical_url/);
  });

  it('is idempotent — skips the insert when the live natural key exists', async () => {
    const { env, sqlLog } = makeStub({ existing: { id: 'link_existing' } });
    const res = await mirrorArtifactLink(env, 'tasks', 'task_X', URL_, 'Hermes: Plan', MOCK_USER);
    expect(res).toBe('already_present');
    expect(sqlLog.some((s) => /^INSERT INTO links/i.test(s.trim()))).toBe(false);
  });

  it('skips a URL with no art_ id without touching the DB', async () => {
    const { env, sqlLog } = makeStub();
    const res = await mirrorArtifactLink(env, 'tasks', 'task_X', 'https://example.com/x', 'd', MOCK_USER);
    expect(res).toBe('skipped_no_id');
    expect(sqlLog).toHaveLength(0);
  });

  it('never throws — a DB error yields "failed", leaving the slot as fallback', async () => {
    const spy = vi.spyOn(console, 'error').mockImplementation(() => {});
    const { env } = makeStub({ existing: null, throwOnInsert: true });
    const res = await mirrorArtifactLink(env, 'tasks', 'task_X', URL_, 'd', MOCK_USER);
    expect(res).toBe('failed');
    spy.mockRestore();
  });

  it('appends sort_order after existing links (MAX+1)', async () => {
    const { env, sqlLog } = makeStub({ existing: null, maxSortOrder: 2 });
    const res = await mirrorArtifactLink(env, 'tasks', 'task_X', URL_, 'd', MOCK_USER);
    expect(res).toBe('inserted');
    // The MAX(sort_order) probe must have run (sort_order = 2 + 1 = 3).
    expect(sqlLog.some((s) => /MAX\(sort_order\)/i.test(s))).toBe(true);
  });

  // Reference CANON so an accidental contract host change fails the file too.
  it('canonical constant tracks the prod host', () => {
    expect(artifactCanonicalUrl(URL_)).toBe(CANON);
  });
});
