// artifact-link-mirror.test.ts — #196 artifact -> links-table mirror.
//
// The load-bearing invariant is CANONICAL PARITY: the in-api canonical
// (artifactCanonicalUrl) must byte-match what PB's link contract produces, or a
// Hub-created links row and a PB-pushed one won't dedup on the
// (owner,role,canonical_url) partial-UNIQUE. The cross-repo parity test below
// pins it to the generated fixture corpus (the same corpus the pbLinks vitest
// asserts against), so the api/ copy can't silently drift from the contract.

import { describe, it, expect, vi } from 'vitest';
import { artifactCanonicalUrl, mirrorArtifactLink } from './artifact-link-mirror';
import type { Env, AuthUser } from '../helpers';
import { prodSchemaDb, d1Adapter, insertRow } from '../test-support/prod-schema-db';
// api tests may cross the runtime bundle boundary into src/ (precedent:
// api/routes/optimistic-rollback.test.ts). The corpus is generated by PB's
// gen_links.py from the single authored contract.
import fixtures from '../../src/lib/__tests__/link-fixtures.json';

const MOCK_USER: AuthUser = { email: 'ingra107@umn.edu', slug: 'nick-ingraham', isPi: true };

describe('artifactCanonicalUrl — host-normalized canonical', () => {
  it('canonicalizes a prod artifact URL on the stable art_ id', () => {
    expect(artifactCanonicalUrl('https://mn-ccore-lab.pages.dev/portal/artifacts/art_0a1b2c3d')).toBe(
      'https://mn-ccore-lab.pages.dev/portal/artifacts/art_0a1b2c3d',
    );
  });

  it('collapses a non-prod capture origin to the prod canonical (dedup safety)', () => {
    // A staging / preview / custom-domain origin must yield the SAME canonical,
    // else a Hub-created row and a PB-pushed row fork the natural key.
    expect(artifactCanonicalUrl('https://mnccore-lab-test.pages.dev/portal/artifacts/art_0a1b2c3d')).toBe(
      'https://mn-ccore-lab.pages.dev/portal/artifacts/art_0a1b2c3d',
    );
  });

  it('extracts the id from a URL embedded in markdown / trailing punctuation', () => {
    expect(artifactCanonicalUrl('see [the doc](https://mn-ccore-lab.pages.dev/portal/artifacts/art_deadbeef)')).toBe(
      'https://mn-ccore-lab.pages.dev/portal/artifacts/art_deadbeef',
    );
  });

  it('returns null for a URL with no art_<hex> id', () => {
    expect(artifactCanonicalUrl('https://mn-ccore-lab.pages.dev/portal/projects/abc')).toBeNull();
  });
});

describe('cross-repo parity: api canonical == PB contract corpus', () => {
  it('matches the generated artifact fixture canonical_url byte-for-byte', () => {
    const artifactCase = (fixtures as Array<{ raw: string; expected: { type: string; canonical_url: string } }>)
      .find((c) => c.expected.type === 'artifact');
    expect(artifactCase, 'no artifact fixture in the corpus — gen_links.py must emit one').toBeTruthy();
    expect(artifactCanonicalUrl(artifactCase!.raw)).toBe(artifactCase!.expected.canonical_url);
  });
});

// ── mirrorArtifactLink ──────────────────────────────────────────────────────
//
// #8875: runs on the migration-chain database (api/test-support/prod-schema-db.ts).
// The old stub matched the pre-check / MAX / readCanonical SQL by text, stored a
// synthetic {id, seq} on INSERT and only asserted that INSERT text was issued.
// Here the schema-v88 links table, its NOT NULLs, its CHECK on owner_table, the
// live partial UNIQUE on (owner, role, canonical_url) and the seq trigger are
// the real ones, and every case reads the stored rows back.

type DB = ReturnType<typeof prodSchemaDb>;

function setup(opts: { precheckLosesRace?: boolean } = {}) {
  const db = prodSchemaDb();
  const sqlLog: string[] = [];
  const base = d1Adapter(db, { onExec: (sql) => { sqlLog.push(sql); } });
  // precheckLosesRace: the natural-key pre-check answers "absent" without
  // reaching the engine, as it would if a peer inserted between the pre-check
  // and the INSERT. Every other statement runs for real.
  const DB = opts.precheckLosesRace
    ? {
        ...base,
        prepare: (sql: string) => {
          const s = base.prepare(sql);
          if (!(/SELECT id FROM links/.test(sql) && /canonical_url = \?/.test(sql))) return s;
          return { ...s, bind: (...v: unknown[]) => ({ ...s.bind(...v), first: async () => null }) };
        },
      }
    : base;
  return { db, sqlLog, env: { DB } as unknown as Env };
}

const linksOf = (db: DB, ownerId: string) =>
  db.prepare('SELECT * FROM links WHERE owner_id = ? ORDER BY sort_order').all(ownerId) as Array<Record<string, unknown>>;

function seedLink(db: DB, id: string, ownerId: string, canonical: string, sortOrder: number, deletedAt: string | null = null) {
  insertRow(db, 'links', {
    id, owner_table: 'tasks', owner_id: ownerId, role: 'key', type: 'artifact',
    canonical_url: canonical, short_title: id, sort_order: sortOrder, deleted_at: deletedAt,
  });
}

describe('mirrorArtifactLink', () => {
  const URL_ = 'https://mn-ccore-lab.pages.dev/portal/artifacts/art_abc123';
  const CANON = 'https://mn-ccore-lab.pages.dev/portal/artifacts/art_abc123';
  const STAGING_URL = 'https://mnccore-lab-test.pages.dev/portal/artifacts/art_abc123';

  it('inserts a synced links row for a fresh artifact URL', async () => {
    const { db, env } = setup();
    const res = await mirrorArtifactLink(env, 'tasks', 'task_X', URL_, 'Hermes: Plan', MOCK_USER);
    expect(res).toBe('inserted');
    const rows = linksOf(db, 'task_X');
    expect(rows).toHaveLength(1);
    expect(rows[0]).toMatchObject({
      owner_table: 'tasks', owner_id: 'task_X', role: 'key', type: 'artifact',
      canonical_url: CANON, short_title: 'Hermes: Plan', source_raw: null, sort_order: 0, deleted_at: null,
    });
    // The seq trigger assigned a pull-cursor position and the write stamped its mutation id.
    expect(rows[0].seq).toBeGreaterThan(0);
    expect(String(rows[0].last_mutation_id)).toMatch(/^mut_/);
  });

  it('stores the prod-origin canonical and keeps a non-prod raw URL as source_raw', async () => {
    const { db, env } = setup();
    expect(await mirrorArtifactLink(env, 'projects', 'proj_Y', STAGING_URL, 'd', MOCK_USER)).toBe('inserted');
    const rows = db.prepare("SELECT * FROM links WHERE owner_table = 'projects' AND owner_id = 'proj_Y'").all() as Array<Record<string, unknown>>;
    expect(rows).toHaveLength(1);
    expect(rows[0].canonical_url).toBe(CANON);
    expect(rows[0].source_raw).toBe(STAGING_URL);
  });

  it('is idempotent — skips the insert when the live natural key exists', async () => {
    const { db, env, sqlLog } = setup();
    seedLink(db, 'link_existing', 'task_X', CANON, 0);
    const res = await mirrorArtifactLink(env, 'tasks', 'task_X', URL_, 'Hermes: Plan', MOCK_USER);
    expect(res).toBe('already_present');
    expect(linksOf(db, 'task_X').map((r) => r.id)).toEqual(['link_existing']);
    expect(sqlLog.some((s) => /^\s*INSERT\b/i.test(s))).toBe(false);
  });

  it('re-adds a URL whose only row is soft-deleted (the natural key covers live rows only)', async () => {
    const { db, env } = setup();
    seedLink(db, 'link_gone', 'task_X', CANON, 0, '2026-09-01 00:00:00');
    expect(await mirrorArtifactLink(env, 'tasks', 'task_X', URL_, 'd', MOCK_USER)).toBe('inserted');
    const live = linksOf(db, 'task_X').filter((r) => r.deleted_at === null);
    expect(live).toHaveLength(1);
    expect(live[0].id).not.toBe('link_gone');
  });

  it('skips a URL with no art_ id without touching the DB', async () => {
    const { db, env, sqlLog } = setup();
    const res = await mirrorArtifactLink(env, 'tasks', 'task_X', 'https://example.com/x', 'd', MOCK_USER);
    expect(res).toBe('skipped_no_id');
    expect(sqlLog).toHaveLength(0);
    expect(linksOf(db, 'task_X')).toHaveLength(0);
  });

  it('never throws — a lost pre-check race hits the live UNIQUE and yields "failed"', async () => {
    // The INSERT reaches the real partial UNIQUE and is refused. The mirror
    // must contain that error: its callers (artifact create, comment post) must
    // not 500 over a non-critical link mirror; the slot stays the fallback.
    const spy = vi.spyOn(console, 'error').mockImplementation(() => {});
    const { db, env } = setup({ precheckLosesRace: true });
    seedLink(db, 'link_racer', 'task_X', CANON, 0);
    const res = await mirrorArtifactLink(env, 'tasks', 'task_X', URL_, 'd', MOCK_USER);
    expect(res).toBe('failed');
    expect(spy).toHaveBeenCalledTimes(1);
    expect(String(spy.mock.calls[0][1])).toMatch(/UNIQUE constraint failed/);
    expect(linksOf(db, 'task_X').map((r) => r.id)).toEqual(['link_racer']);
    spy.mockRestore();
  });

  it('never throws — a D1 error on the insert yields "failed" and writes nothing', async () => {
    const spy = vi.spyOn(console, 'error').mockImplementation(() => {});
    const db = prodSchemaDb();
    const env = { DB: d1Adapter(db, { failSql: /^\s*INSERT INTO links/i, failTimes: 1 }) } as unknown as Env;
    expect(await mirrorArtifactLink(env, 'tasks', 'task_X', URL_, 'd', MOCK_USER)).toBe('failed');
    expect(spy).toHaveBeenCalledTimes(1);
    expect(linksOf(db, 'task_X')).toHaveLength(0);
    spy.mockRestore();
  });

  it('appends sort_order after the live links (MAX+1), ignoring tombstones and other owners', async () => {
    const { db, env } = setup();
    seedLink(db, 'link_a', 'task_X', 'https://example.com/a', 0);
    seedLink(db, 'link_b', 'task_X', 'https://example.com/b', 2);
    seedLink(db, 'link_dead', 'task_X', 'https://example.com/dead', 9, '2026-09-01 00:00:00');
    seedLink(db, 'link_other', 'task_OTHER', 'https://example.com/o', 7);
    expect(await mirrorArtifactLink(env, 'tasks', 'task_X', URL_, 'd', MOCK_USER)).toBe('inserted');
    const added = linksOf(db, 'task_X').find((r) => r.canonical_url === CANON);
    expect(added?.sort_order).toBe(3);
  });

  // Reference CANON so an accidental contract host change fails the file too.
  it('canonical constant tracks the prod host', () => {
    expect(artifactCanonicalUrl(URL_)).toBe(CANON);
  });
});
