-- 2026-04-19 Phase 36b: rename team_members slugs to preferred_name-last_name.
-- Current slugs are inconsistent (2 directors as first-name, 17 members as
-- last-name). This migration converges everyone on `preferred-last` so
-- /team/:slug is uniform and Nick's own /team/nick-ingraham works.
-- Approach per member: INSERT new row (copy of old) with new id+slug,
-- UPDATE all referring columns, DELETE old row. FK on comments.author_id
-- stays valid throughout because both rows exist during the UPDATE phase.

-- ─── nick → nick-ingraham ────────────────────────────────────────────
INSERT INTO team_members (id, name, role, credentials, slug, photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at)
  SELECT 'nick-ingraham', name, role, credentials, 'nick-ingraham', photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at
  FROM team_members WHERE id = 'nick';
UPDATE activity_log SET actor = 'nick-ingraham' WHERE actor = 'nick';
UPDATE action_items SET assignee = 'nick-ingraham' WHERE assignee = 'nick';
UPDATE action_items SET completed_by = 'nick-ingraham' WHERE completed_by = 'nick';
UPDATE action_items SET created_by = 'nick-ingraham' WHERE created_by = 'nick';
UPDATE agenda_items SET added_by = 'nick-ingraham' WHERE added_by = 'nick';
UPDATE ai_requests SET requested_by = 'nick-ingraham' WHERE requested_by = 'nick';
UPDATE commitments SET to_whom = 'nick-ingraham' WHERE to_whom = 'nick';
UPDATE contributions SET member_slug = 'nick-ingraham' WHERE member_slug = 'nick';
UPDATE hub_decisions SET decided_by = 'nick-ingraham' WHERE decided_by = 'nick';
UPDATE digest_comments SET author_slug = 'nick-ingraham' WHERE author_slug = 'nick';
UPDATE expertise_tags SET member_slug = 'nick-ingraham' WHERE member_slug = 'nick';
UPDATE file_attachments SET uploaded_by = 'nick-ingraham' WHERE uploaded_by = 'nick';
UPDATE grants SET pi = 'nick-ingraham' WHERE pi = 'nick';
UPDATE ideas SET submitted_by = 'nick-ingraham' WHERE submitted_by = 'nick';
UPDATE inbox SET author = 'nick-ingraham' WHERE author = 'nick';
UPDATE lab_answers SET author_slug = 'nick-ingraham' WHERE author_slug = 'nick';
UPDATE lab_questions SET asked_by = 'nick-ingraham' WHERE asked_by = 'nick';
UPDATE mentee_milestones SET mentee_slug = 'nick-ingraham' WHERE mentee_slug = 'nick';
UPDATE milestones SET future_note_author = 'nick-ingraham' WHERE future_note_author = 'nick';
UPDATE notifications SET recipient_slug = 'nick-ingraham' WHERE recipient_slug = 'nick';
UPDATE paper_project_links SET linked_by = 'nick-ingraham' WHERE linked_by = 'nick';
UPDATE project_dependencies SET created_by = 'nick-ingraham' WHERE created_by = 'nick';
UPDATE project_documents SET created_by = 'nick-ingraham' WHERE created_by = 'nick';
UPDATE project_updates SET author = 'nick-ingraham' WHERE author = 'nick';
UPDATE projects SET pi = 'nick-ingraham' WHERE pi = 'nick';
UPDATE reactions SET user_slug = 'nick-ingraham' WHERE user_slug = 'nick';
UPDATE research_digest SET saved_by = 'nick-ingraham' WHERE saved_by = 'nick';
UPDATE research_narratives SET created_by = 'nick-ingraham' WHERE created_by = 'nick';
UPDATE tasks SET assignee = 'nick-ingraham' WHERE assignee = 'nick';
UPDATE tasks SET assigned_by = 'nick-ingraham' WHERE assigned_by = 'nick';
UPDATE tasks SET completed_by = 'nick-ingraham' WHERE completed_by = 'nick';
UPDATE tasks SET acknowledged_by = 'nick-ingraham' WHERE acknowledged_by = 'nick';
UPDATE task_comments SET author_slug = 'nick-ingraham' WHERE author_slug = 'nick';
UPDATE task_files SET uploaded_by = 'nick-ingraham' WHERE uploaded_by = 'nick';
UPDATE task_handoffs SET from_slug = 'nick-ingraham' WHERE from_slug = 'nick';
UPDATE task_handoffs SET to_slug = 'nick-ingraham' WHERE to_slug = 'nick';
UPDATE task_subtasks SET completed_by = 'nick-ingraham' WHERE completed_by = 'nick';
UPDATE task_updates SET author_slug = 'nick-ingraham' WHERE author_slug = 'nick';
UPDATE trainee_milestones SET member_slug = 'nick-ingraham' WHERE member_slug = 'nick';
UPDATE watchlist SET member_slug = 'nick-ingraham' WHERE member_slug = 'nick';
UPDATE comments SET author_id = 'nick-ingraham' WHERE author_id = 'nick';
DELETE FROM team_members WHERE id = 'nick';

-- ─── nate → nate-mesfin ────────────────────────────────────────────
INSERT INTO team_members (id, name, role, credentials, slug, photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at)
  SELECT 'nate-mesfin', name, role, credentials, 'nate-mesfin', photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at
  FROM team_members WHERE id = 'nate';
UPDATE activity_log SET actor = 'nate-mesfin' WHERE actor = 'nate';
UPDATE action_items SET assignee = 'nate-mesfin' WHERE assignee = 'nate';
UPDATE action_items SET completed_by = 'nate-mesfin' WHERE completed_by = 'nate';
UPDATE action_items SET created_by = 'nate-mesfin' WHERE created_by = 'nate';
UPDATE agenda_items SET added_by = 'nate-mesfin' WHERE added_by = 'nate';
UPDATE ai_requests SET requested_by = 'nate-mesfin' WHERE requested_by = 'nate';
UPDATE commitments SET to_whom = 'nate-mesfin' WHERE to_whom = 'nate';
UPDATE contributions SET member_slug = 'nate-mesfin' WHERE member_slug = 'nate';
UPDATE hub_decisions SET decided_by = 'nate-mesfin' WHERE decided_by = 'nate';
UPDATE digest_comments SET author_slug = 'nate-mesfin' WHERE author_slug = 'nate';
UPDATE expertise_tags SET member_slug = 'nate-mesfin' WHERE member_slug = 'nate';
UPDATE file_attachments SET uploaded_by = 'nate-mesfin' WHERE uploaded_by = 'nate';
UPDATE grants SET pi = 'nate-mesfin' WHERE pi = 'nate';
UPDATE ideas SET submitted_by = 'nate-mesfin' WHERE submitted_by = 'nate';
UPDATE inbox SET author = 'nate-mesfin' WHERE author = 'nate';
UPDATE lab_answers SET author_slug = 'nate-mesfin' WHERE author_slug = 'nate';
UPDATE lab_questions SET asked_by = 'nate-mesfin' WHERE asked_by = 'nate';
UPDATE mentee_milestones SET mentee_slug = 'nate-mesfin' WHERE mentee_slug = 'nate';
UPDATE milestones SET future_note_author = 'nate-mesfin' WHERE future_note_author = 'nate';
UPDATE notifications SET recipient_slug = 'nate-mesfin' WHERE recipient_slug = 'nate';
UPDATE paper_project_links SET linked_by = 'nate-mesfin' WHERE linked_by = 'nate';
UPDATE project_dependencies SET created_by = 'nate-mesfin' WHERE created_by = 'nate';
UPDATE project_documents SET created_by = 'nate-mesfin' WHERE created_by = 'nate';
UPDATE project_updates SET author = 'nate-mesfin' WHERE author = 'nate';
UPDATE projects SET pi = 'nate-mesfin' WHERE pi = 'nate';
UPDATE reactions SET user_slug = 'nate-mesfin' WHERE user_slug = 'nate';
UPDATE research_digest SET saved_by = 'nate-mesfin' WHERE saved_by = 'nate';
UPDATE research_narratives SET created_by = 'nate-mesfin' WHERE created_by = 'nate';
UPDATE tasks SET assignee = 'nate-mesfin' WHERE assignee = 'nate';
UPDATE tasks SET assigned_by = 'nate-mesfin' WHERE assigned_by = 'nate';
UPDATE tasks SET completed_by = 'nate-mesfin' WHERE completed_by = 'nate';
UPDATE tasks SET acknowledged_by = 'nate-mesfin' WHERE acknowledged_by = 'nate';
UPDATE task_comments SET author_slug = 'nate-mesfin' WHERE author_slug = 'nate';
UPDATE task_files SET uploaded_by = 'nate-mesfin' WHERE uploaded_by = 'nate';
UPDATE task_handoffs SET from_slug = 'nate-mesfin' WHERE from_slug = 'nate';
UPDATE task_handoffs SET to_slug = 'nate-mesfin' WHERE to_slug = 'nate';
UPDATE task_subtasks SET completed_by = 'nate-mesfin' WHERE completed_by = 'nate';
UPDATE task_updates SET author_slug = 'nate-mesfin' WHERE author_slug = 'nate';
UPDATE trainee_milestones SET member_slug = 'nate-mesfin' WHERE member_slug = 'nate';
UPDATE watchlist SET member_slug = 'nate-mesfin' WHERE member_slug = 'nate';
UPDATE comments SET author_id = 'nate-mesfin' WHERE author_id = 'nate';
DELETE FROM team_members WHERE id = 'nate';

-- ─── dudley → adams-dudley ────────────────────────────────────────────
INSERT INTO team_members (id, name, role, credentials, slug, photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at)
  SELECT 'adams-dudley', name, role, credentials, 'adams-dudley', photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at
  FROM team_members WHERE id = 'dudley';
UPDATE activity_log SET actor = 'adams-dudley' WHERE actor = 'dudley';
UPDATE action_items SET assignee = 'adams-dudley' WHERE assignee = 'dudley';
UPDATE action_items SET completed_by = 'adams-dudley' WHERE completed_by = 'dudley';
UPDATE action_items SET created_by = 'adams-dudley' WHERE created_by = 'dudley';
UPDATE agenda_items SET added_by = 'adams-dudley' WHERE added_by = 'dudley';
UPDATE ai_requests SET requested_by = 'adams-dudley' WHERE requested_by = 'dudley';
UPDATE commitments SET to_whom = 'adams-dudley' WHERE to_whom = 'dudley';
UPDATE contributions SET member_slug = 'adams-dudley' WHERE member_slug = 'dudley';
UPDATE hub_decisions SET decided_by = 'adams-dudley' WHERE decided_by = 'dudley';
UPDATE digest_comments SET author_slug = 'adams-dudley' WHERE author_slug = 'dudley';
UPDATE expertise_tags SET member_slug = 'adams-dudley' WHERE member_slug = 'dudley';
UPDATE file_attachments SET uploaded_by = 'adams-dudley' WHERE uploaded_by = 'dudley';
UPDATE grants SET pi = 'adams-dudley' WHERE pi = 'dudley';
UPDATE ideas SET submitted_by = 'adams-dudley' WHERE submitted_by = 'dudley';
UPDATE inbox SET author = 'adams-dudley' WHERE author = 'dudley';
UPDATE lab_answers SET author_slug = 'adams-dudley' WHERE author_slug = 'dudley';
UPDATE lab_questions SET asked_by = 'adams-dudley' WHERE asked_by = 'dudley';
UPDATE mentee_milestones SET mentee_slug = 'adams-dudley' WHERE mentee_slug = 'dudley';
UPDATE milestones SET future_note_author = 'adams-dudley' WHERE future_note_author = 'dudley';
UPDATE notifications SET recipient_slug = 'adams-dudley' WHERE recipient_slug = 'dudley';
UPDATE paper_project_links SET linked_by = 'adams-dudley' WHERE linked_by = 'dudley';
UPDATE project_dependencies SET created_by = 'adams-dudley' WHERE created_by = 'dudley';
UPDATE project_documents SET created_by = 'adams-dudley' WHERE created_by = 'dudley';
UPDATE project_updates SET author = 'adams-dudley' WHERE author = 'dudley';
UPDATE projects SET pi = 'adams-dudley' WHERE pi = 'dudley';
UPDATE reactions SET user_slug = 'adams-dudley' WHERE user_slug = 'dudley';
UPDATE research_digest SET saved_by = 'adams-dudley' WHERE saved_by = 'dudley';
UPDATE research_narratives SET created_by = 'adams-dudley' WHERE created_by = 'dudley';
UPDATE tasks SET assignee = 'adams-dudley' WHERE assignee = 'dudley';
UPDATE tasks SET assigned_by = 'adams-dudley' WHERE assigned_by = 'dudley';
UPDATE tasks SET completed_by = 'adams-dudley' WHERE completed_by = 'dudley';
UPDATE tasks SET acknowledged_by = 'adams-dudley' WHERE acknowledged_by = 'dudley';
UPDATE task_comments SET author_slug = 'adams-dudley' WHERE author_slug = 'dudley';
UPDATE task_files SET uploaded_by = 'adams-dudley' WHERE uploaded_by = 'dudley';
UPDATE task_handoffs SET from_slug = 'adams-dudley' WHERE from_slug = 'dudley';
UPDATE task_handoffs SET to_slug = 'adams-dudley' WHERE to_slug = 'dudley';
UPDATE task_subtasks SET completed_by = 'adams-dudley' WHERE completed_by = 'dudley';
UPDATE task_updates SET author_slug = 'adams-dudley' WHERE author_slug = 'dudley';
UPDATE trainee_milestones SET member_slug = 'adams-dudley' WHERE member_slug = 'dudley';
UPDATE watchlist SET member_slug = 'adams-dudley' WHERE member_slug = 'dudley';
UPDATE comments SET author_id = 'adams-dudley' WHERE author_id = 'dudley';
DELETE FROM team_members WHERE id = 'dudley';

-- ─── chipman → jeff-chipman ────────────────────────────────────────────
INSERT INTO team_members (id, name, role, credentials, slug, photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at)
  SELECT 'jeff-chipman', name, role, credentials, 'jeff-chipman', photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at
  FROM team_members WHERE id = 'chipman';
UPDATE activity_log SET actor = 'jeff-chipman' WHERE actor = 'chipman';
UPDATE action_items SET assignee = 'jeff-chipman' WHERE assignee = 'chipman';
UPDATE action_items SET completed_by = 'jeff-chipman' WHERE completed_by = 'chipman';
UPDATE action_items SET created_by = 'jeff-chipman' WHERE created_by = 'chipman';
UPDATE agenda_items SET added_by = 'jeff-chipman' WHERE added_by = 'chipman';
UPDATE ai_requests SET requested_by = 'jeff-chipman' WHERE requested_by = 'chipman';
UPDATE commitments SET to_whom = 'jeff-chipman' WHERE to_whom = 'chipman';
UPDATE contributions SET member_slug = 'jeff-chipman' WHERE member_slug = 'chipman';
UPDATE hub_decisions SET decided_by = 'jeff-chipman' WHERE decided_by = 'chipman';
UPDATE digest_comments SET author_slug = 'jeff-chipman' WHERE author_slug = 'chipman';
UPDATE expertise_tags SET member_slug = 'jeff-chipman' WHERE member_slug = 'chipman';
UPDATE file_attachments SET uploaded_by = 'jeff-chipman' WHERE uploaded_by = 'chipman';
UPDATE grants SET pi = 'jeff-chipman' WHERE pi = 'chipman';
UPDATE ideas SET submitted_by = 'jeff-chipman' WHERE submitted_by = 'chipman';
UPDATE inbox SET author = 'jeff-chipman' WHERE author = 'chipman';
UPDATE lab_answers SET author_slug = 'jeff-chipman' WHERE author_slug = 'chipman';
UPDATE lab_questions SET asked_by = 'jeff-chipman' WHERE asked_by = 'chipman';
UPDATE mentee_milestones SET mentee_slug = 'jeff-chipman' WHERE mentee_slug = 'chipman';
UPDATE milestones SET future_note_author = 'jeff-chipman' WHERE future_note_author = 'chipman';
UPDATE notifications SET recipient_slug = 'jeff-chipman' WHERE recipient_slug = 'chipman';
UPDATE paper_project_links SET linked_by = 'jeff-chipman' WHERE linked_by = 'chipman';
UPDATE project_dependencies SET created_by = 'jeff-chipman' WHERE created_by = 'chipman';
UPDATE project_documents SET created_by = 'jeff-chipman' WHERE created_by = 'chipman';
UPDATE project_updates SET author = 'jeff-chipman' WHERE author = 'chipman';
UPDATE projects SET pi = 'jeff-chipman' WHERE pi = 'chipman';
UPDATE reactions SET user_slug = 'jeff-chipman' WHERE user_slug = 'chipman';
UPDATE research_digest SET saved_by = 'jeff-chipman' WHERE saved_by = 'chipman';
UPDATE research_narratives SET created_by = 'jeff-chipman' WHERE created_by = 'chipman';
UPDATE tasks SET assignee = 'jeff-chipman' WHERE assignee = 'chipman';
UPDATE tasks SET assigned_by = 'jeff-chipman' WHERE assigned_by = 'chipman';
UPDATE tasks SET completed_by = 'jeff-chipman' WHERE completed_by = 'chipman';
UPDATE tasks SET acknowledged_by = 'jeff-chipman' WHERE acknowledged_by = 'chipman';
UPDATE task_comments SET author_slug = 'jeff-chipman' WHERE author_slug = 'chipman';
UPDATE task_files SET uploaded_by = 'jeff-chipman' WHERE uploaded_by = 'chipman';
UPDATE task_handoffs SET from_slug = 'jeff-chipman' WHERE from_slug = 'chipman';
UPDATE task_handoffs SET to_slug = 'jeff-chipman' WHERE to_slug = 'chipman';
UPDATE task_subtasks SET completed_by = 'jeff-chipman' WHERE completed_by = 'chipman';
UPDATE task_updates SET author_slug = 'jeff-chipman' WHERE author_slug = 'chipman';
UPDATE trainee_milestones SET member_slug = 'jeff-chipman' WHERE member_slug = 'chipman';
UPDATE watchlist SET member_slug = 'jeff-chipman' WHERE member_slug = 'chipman';
UPDATE comments SET author_id = 'jeff-chipman' WHERE author_id = 'chipman';
DELETE FROM team_members WHERE id = 'chipman';

-- ─── mceachron → kendall-mceachron ────────────────────────────────────────────
INSERT INTO team_members (id, name, role, credentials, slug, photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at)
  SELECT 'kendall-mceachron', name, role, credentials, 'kendall-mceachron', photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at
  FROM team_members WHERE id = 'mceachron';
UPDATE activity_log SET actor = 'kendall-mceachron' WHERE actor = 'mceachron';
UPDATE action_items SET assignee = 'kendall-mceachron' WHERE assignee = 'mceachron';
UPDATE action_items SET completed_by = 'kendall-mceachron' WHERE completed_by = 'mceachron';
UPDATE action_items SET created_by = 'kendall-mceachron' WHERE created_by = 'mceachron';
UPDATE agenda_items SET added_by = 'kendall-mceachron' WHERE added_by = 'mceachron';
UPDATE ai_requests SET requested_by = 'kendall-mceachron' WHERE requested_by = 'mceachron';
UPDATE commitments SET to_whom = 'kendall-mceachron' WHERE to_whom = 'mceachron';
UPDATE contributions SET member_slug = 'kendall-mceachron' WHERE member_slug = 'mceachron';
UPDATE hub_decisions SET decided_by = 'kendall-mceachron' WHERE decided_by = 'mceachron';
UPDATE digest_comments SET author_slug = 'kendall-mceachron' WHERE author_slug = 'mceachron';
UPDATE expertise_tags SET member_slug = 'kendall-mceachron' WHERE member_slug = 'mceachron';
UPDATE file_attachments SET uploaded_by = 'kendall-mceachron' WHERE uploaded_by = 'mceachron';
UPDATE grants SET pi = 'kendall-mceachron' WHERE pi = 'mceachron';
UPDATE ideas SET submitted_by = 'kendall-mceachron' WHERE submitted_by = 'mceachron';
UPDATE inbox SET author = 'kendall-mceachron' WHERE author = 'mceachron';
UPDATE lab_answers SET author_slug = 'kendall-mceachron' WHERE author_slug = 'mceachron';
UPDATE lab_questions SET asked_by = 'kendall-mceachron' WHERE asked_by = 'mceachron';
UPDATE mentee_milestones SET mentee_slug = 'kendall-mceachron' WHERE mentee_slug = 'mceachron';
UPDATE milestones SET future_note_author = 'kendall-mceachron' WHERE future_note_author = 'mceachron';
UPDATE notifications SET recipient_slug = 'kendall-mceachron' WHERE recipient_slug = 'mceachron';
UPDATE paper_project_links SET linked_by = 'kendall-mceachron' WHERE linked_by = 'mceachron';
UPDATE project_dependencies SET created_by = 'kendall-mceachron' WHERE created_by = 'mceachron';
UPDATE project_documents SET created_by = 'kendall-mceachron' WHERE created_by = 'mceachron';
UPDATE project_updates SET author = 'kendall-mceachron' WHERE author = 'mceachron';
UPDATE projects SET pi = 'kendall-mceachron' WHERE pi = 'mceachron';
UPDATE reactions SET user_slug = 'kendall-mceachron' WHERE user_slug = 'mceachron';
UPDATE research_digest SET saved_by = 'kendall-mceachron' WHERE saved_by = 'mceachron';
UPDATE research_narratives SET created_by = 'kendall-mceachron' WHERE created_by = 'mceachron';
UPDATE tasks SET assignee = 'kendall-mceachron' WHERE assignee = 'mceachron';
UPDATE tasks SET assigned_by = 'kendall-mceachron' WHERE assigned_by = 'mceachron';
UPDATE tasks SET completed_by = 'kendall-mceachron' WHERE completed_by = 'mceachron';
UPDATE tasks SET acknowledged_by = 'kendall-mceachron' WHERE acknowledged_by = 'mceachron';
UPDATE task_comments SET author_slug = 'kendall-mceachron' WHERE author_slug = 'mceachron';
UPDATE task_files SET uploaded_by = 'kendall-mceachron' WHERE uploaded_by = 'mceachron';
UPDATE task_handoffs SET from_slug = 'kendall-mceachron' WHERE from_slug = 'mceachron';
UPDATE task_handoffs SET to_slug = 'kendall-mceachron' WHERE to_slug = 'mceachron';
UPDATE task_subtasks SET completed_by = 'kendall-mceachron' WHERE completed_by = 'mceachron';
UPDATE task_updates SET author_slug = 'kendall-mceachron' WHERE author_slug = 'mceachron';
UPDATE trainee_milestones SET member_slug = 'kendall-mceachron' WHERE member_slug = 'mceachron';
UPDATE watchlist SET member_slug = 'kendall-mceachron' WHERE member_slug = 'mceachron';
UPDATE comments SET author_id = 'kendall-mceachron' WHERE author_id = 'mceachron';
DELETE FROM team_members WHERE id = 'mceachron';

-- ─── safadi → sami-safadi ────────────────────────────────────────────
INSERT INTO team_members (id, name, role, credentials, slug, photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at)
  SELECT 'sami-safadi', name, role, credentials, 'sami-safadi', photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at
  FROM team_members WHERE id = 'safadi';
UPDATE activity_log SET actor = 'sami-safadi' WHERE actor = 'safadi';
UPDATE action_items SET assignee = 'sami-safadi' WHERE assignee = 'safadi';
UPDATE action_items SET completed_by = 'sami-safadi' WHERE completed_by = 'safadi';
UPDATE action_items SET created_by = 'sami-safadi' WHERE created_by = 'safadi';
UPDATE agenda_items SET added_by = 'sami-safadi' WHERE added_by = 'safadi';
UPDATE ai_requests SET requested_by = 'sami-safadi' WHERE requested_by = 'safadi';
UPDATE commitments SET to_whom = 'sami-safadi' WHERE to_whom = 'safadi';
UPDATE contributions SET member_slug = 'sami-safadi' WHERE member_slug = 'safadi';
UPDATE hub_decisions SET decided_by = 'sami-safadi' WHERE decided_by = 'safadi';
UPDATE digest_comments SET author_slug = 'sami-safadi' WHERE author_slug = 'safadi';
UPDATE expertise_tags SET member_slug = 'sami-safadi' WHERE member_slug = 'safadi';
UPDATE file_attachments SET uploaded_by = 'sami-safadi' WHERE uploaded_by = 'safadi';
UPDATE grants SET pi = 'sami-safadi' WHERE pi = 'safadi';
UPDATE ideas SET submitted_by = 'sami-safadi' WHERE submitted_by = 'safadi';
UPDATE inbox SET author = 'sami-safadi' WHERE author = 'safadi';
UPDATE lab_answers SET author_slug = 'sami-safadi' WHERE author_slug = 'safadi';
UPDATE lab_questions SET asked_by = 'sami-safadi' WHERE asked_by = 'safadi';
UPDATE mentee_milestones SET mentee_slug = 'sami-safadi' WHERE mentee_slug = 'safadi';
UPDATE milestones SET future_note_author = 'sami-safadi' WHERE future_note_author = 'safadi';
UPDATE notifications SET recipient_slug = 'sami-safadi' WHERE recipient_slug = 'safadi';
UPDATE paper_project_links SET linked_by = 'sami-safadi' WHERE linked_by = 'safadi';
UPDATE project_dependencies SET created_by = 'sami-safadi' WHERE created_by = 'safadi';
UPDATE project_documents SET created_by = 'sami-safadi' WHERE created_by = 'safadi';
UPDATE project_updates SET author = 'sami-safadi' WHERE author = 'safadi';
UPDATE projects SET pi = 'sami-safadi' WHERE pi = 'safadi';
UPDATE reactions SET user_slug = 'sami-safadi' WHERE user_slug = 'safadi';
UPDATE research_digest SET saved_by = 'sami-safadi' WHERE saved_by = 'safadi';
UPDATE research_narratives SET created_by = 'sami-safadi' WHERE created_by = 'safadi';
UPDATE tasks SET assignee = 'sami-safadi' WHERE assignee = 'safadi';
UPDATE tasks SET assigned_by = 'sami-safadi' WHERE assigned_by = 'safadi';
UPDATE tasks SET completed_by = 'sami-safadi' WHERE completed_by = 'safadi';
UPDATE tasks SET acknowledged_by = 'sami-safadi' WHERE acknowledged_by = 'safadi';
UPDATE task_comments SET author_slug = 'sami-safadi' WHERE author_slug = 'safadi';
UPDATE task_files SET uploaded_by = 'sami-safadi' WHERE uploaded_by = 'safadi';
UPDATE task_handoffs SET from_slug = 'sami-safadi' WHERE from_slug = 'safadi';
UPDATE task_handoffs SET to_slug = 'sami-safadi' WHERE to_slug = 'safadi';
UPDATE task_subtasks SET completed_by = 'sami-safadi' WHERE completed_by = 'safadi';
UPDATE task_updates SET author_slug = 'sami-safadi' WHERE author_slug = 'safadi';
UPDATE trainee_milestones SET member_slug = 'sami-safadi' WHERE member_slug = 'safadi';
UPDATE watchlist SET member_slug = 'sami-safadi' WHERE member_slug = 'safadi';
UPDATE comments SET author_id = 'sami-safadi' WHERE author_id = 'safadi';
DELETE FROM team_members WHERE id = 'safadi';

-- ─── begnaud → abbie-begnaud ────────────────────────────────────────────
INSERT INTO team_members (id, name, role, credentials, slug, photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at)
  SELECT 'abbie-begnaud', name, role, credentials, 'abbie-begnaud', photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at
  FROM team_members WHERE id = 'begnaud';
UPDATE activity_log SET actor = 'abbie-begnaud' WHERE actor = 'begnaud';
UPDATE action_items SET assignee = 'abbie-begnaud' WHERE assignee = 'begnaud';
UPDATE action_items SET completed_by = 'abbie-begnaud' WHERE completed_by = 'begnaud';
UPDATE action_items SET created_by = 'abbie-begnaud' WHERE created_by = 'begnaud';
UPDATE agenda_items SET added_by = 'abbie-begnaud' WHERE added_by = 'begnaud';
UPDATE ai_requests SET requested_by = 'abbie-begnaud' WHERE requested_by = 'begnaud';
UPDATE commitments SET to_whom = 'abbie-begnaud' WHERE to_whom = 'begnaud';
UPDATE contributions SET member_slug = 'abbie-begnaud' WHERE member_slug = 'begnaud';
UPDATE hub_decisions SET decided_by = 'abbie-begnaud' WHERE decided_by = 'begnaud';
UPDATE digest_comments SET author_slug = 'abbie-begnaud' WHERE author_slug = 'begnaud';
UPDATE expertise_tags SET member_slug = 'abbie-begnaud' WHERE member_slug = 'begnaud';
UPDATE file_attachments SET uploaded_by = 'abbie-begnaud' WHERE uploaded_by = 'begnaud';
UPDATE grants SET pi = 'abbie-begnaud' WHERE pi = 'begnaud';
UPDATE ideas SET submitted_by = 'abbie-begnaud' WHERE submitted_by = 'begnaud';
UPDATE inbox SET author = 'abbie-begnaud' WHERE author = 'begnaud';
UPDATE lab_answers SET author_slug = 'abbie-begnaud' WHERE author_slug = 'begnaud';
UPDATE lab_questions SET asked_by = 'abbie-begnaud' WHERE asked_by = 'begnaud';
UPDATE mentee_milestones SET mentee_slug = 'abbie-begnaud' WHERE mentee_slug = 'begnaud';
UPDATE milestones SET future_note_author = 'abbie-begnaud' WHERE future_note_author = 'begnaud';
UPDATE notifications SET recipient_slug = 'abbie-begnaud' WHERE recipient_slug = 'begnaud';
UPDATE paper_project_links SET linked_by = 'abbie-begnaud' WHERE linked_by = 'begnaud';
UPDATE project_dependencies SET created_by = 'abbie-begnaud' WHERE created_by = 'begnaud';
UPDATE project_documents SET created_by = 'abbie-begnaud' WHERE created_by = 'begnaud';
UPDATE project_updates SET author = 'abbie-begnaud' WHERE author = 'begnaud';
UPDATE projects SET pi = 'abbie-begnaud' WHERE pi = 'begnaud';
UPDATE reactions SET user_slug = 'abbie-begnaud' WHERE user_slug = 'begnaud';
UPDATE research_digest SET saved_by = 'abbie-begnaud' WHERE saved_by = 'begnaud';
UPDATE research_narratives SET created_by = 'abbie-begnaud' WHERE created_by = 'begnaud';
UPDATE tasks SET assignee = 'abbie-begnaud' WHERE assignee = 'begnaud';
UPDATE tasks SET assigned_by = 'abbie-begnaud' WHERE assigned_by = 'begnaud';
UPDATE tasks SET completed_by = 'abbie-begnaud' WHERE completed_by = 'begnaud';
UPDATE tasks SET acknowledged_by = 'abbie-begnaud' WHERE acknowledged_by = 'begnaud';
UPDATE task_comments SET author_slug = 'abbie-begnaud' WHERE author_slug = 'begnaud';
UPDATE task_files SET uploaded_by = 'abbie-begnaud' WHERE uploaded_by = 'begnaud';
UPDATE task_handoffs SET from_slug = 'abbie-begnaud' WHERE from_slug = 'begnaud';
UPDATE task_handoffs SET to_slug = 'abbie-begnaud' WHERE to_slug = 'begnaud';
UPDATE task_subtasks SET completed_by = 'abbie-begnaud' WHERE completed_by = 'begnaud';
UPDATE task_updates SET author_slug = 'abbie-begnaud' WHERE author_slug = 'begnaud';
UPDATE trainee_milestones SET member_slug = 'abbie-begnaud' WHERE member_slug = 'begnaud';
UPDATE watchlist SET member_slug = 'abbie-begnaud' WHERE member_slug = 'begnaud';
UPDATE comments SET author_id = 'abbie-begnaud' WHERE author_id = 'begnaud';
DELETE FROM team_members WHERE id = 'begnaud';

-- ─── henkle → benjamin-henkle ────────────────────────────────────────────
INSERT INTO team_members (id, name, role, credentials, slug, photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at)
  SELECT 'benjamin-henkle', name, role, credentials, 'benjamin-henkle', photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at
  FROM team_members WHERE id = 'henkle';
UPDATE activity_log SET actor = 'benjamin-henkle' WHERE actor = 'henkle';
UPDATE action_items SET assignee = 'benjamin-henkle' WHERE assignee = 'henkle';
UPDATE action_items SET completed_by = 'benjamin-henkle' WHERE completed_by = 'henkle';
UPDATE action_items SET created_by = 'benjamin-henkle' WHERE created_by = 'henkle';
UPDATE agenda_items SET added_by = 'benjamin-henkle' WHERE added_by = 'henkle';
UPDATE ai_requests SET requested_by = 'benjamin-henkle' WHERE requested_by = 'henkle';
UPDATE commitments SET to_whom = 'benjamin-henkle' WHERE to_whom = 'henkle';
UPDATE contributions SET member_slug = 'benjamin-henkle' WHERE member_slug = 'henkle';
UPDATE hub_decisions SET decided_by = 'benjamin-henkle' WHERE decided_by = 'henkle';
UPDATE digest_comments SET author_slug = 'benjamin-henkle' WHERE author_slug = 'henkle';
UPDATE expertise_tags SET member_slug = 'benjamin-henkle' WHERE member_slug = 'henkle';
UPDATE file_attachments SET uploaded_by = 'benjamin-henkle' WHERE uploaded_by = 'henkle';
UPDATE grants SET pi = 'benjamin-henkle' WHERE pi = 'henkle';
UPDATE ideas SET submitted_by = 'benjamin-henkle' WHERE submitted_by = 'henkle';
UPDATE inbox SET author = 'benjamin-henkle' WHERE author = 'henkle';
UPDATE lab_answers SET author_slug = 'benjamin-henkle' WHERE author_slug = 'henkle';
UPDATE lab_questions SET asked_by = 'benjamin-henkle' WHERE asked_by = 'henkle';
UPDATE mentee_milestones SET mentee_slug = 'benjamin-henkle' WHERE mentee_slug = 'henkle';
UPDATE milestones SET future_note_author = 'benjamin-henkle' WHERE future_note_author = 'henkle';
UPDATE notifications SET recipient_slug = 'benjamin-henkle' WHERE recipient_slug = 'henkle';
UPDATE paper_project_links SET linked_by = 'benjamin-henkle' WHERE linked_by = 'henkle';
UPDATE project_dependencies SET created_by = 'benjamin-henkle' WHERE created_by = 'henkle';
UPDATE project_documents SET created_by = 'benjamin-henkle' WHERE created_by = 'henkle';
UPDATE project_updates SET author = 'benjamin-henkle' WHERE author = 'henkle';
UPDATE projects SET pi = 'benjamin-henkle' WHERE pi = 'henkle';
UPDATE reactions SET user_slug = 'benjamin-henkle' WHERE user_slug = 'henkle';
UPDATE research_digest SET saved_by = 'benjamin-henkle' WHERE saved_by = 'henkle';
UPDATE research_narratives SET created_by = 'benjamin-henkle' WHERE created_by = 'henkle';
UPDATE tasks SET assignee = 'benjamin-henkle' WHERE assignee = 'henkle';
UPDATE tasks SET assigned_by = 'benjamin-henkle' WHERE assigned_by = 'henkle';
UPDATE tasks SET completed_by = 'benjamin-henkle' WHERE completed_by = 'henkle';
UPDATE tasks SET acknowledged_by = 'benjamin-henkle' WHERE acknowledged_by = 'henkle';
UPDATE task_comments SET author_slug = 'benjamin-henkle' WHERE author_slug = 'henkle';
UPDATE task_files SET uploaded_by = 'benjamin-henkle' WHERE uploaded_by = 'henkle';
UPDATE task_handoffs SET from_slug = 'benjamin-henkle' WHERE from_slug = 'henkle';
UPDATE task_handoffs SET to_slug = 'benjamin-henkle' WHERE to_slug = 'henkle';
UPDATE task_subtasks SET completed_by = 'benjamin-henkle' WHERE completed_by = 'henkle';
UPDATE task_updates SET author_slug = 'benjamin-henkle' WHERE author_slug = 'henkle';
UPDATE trainee_milestones SET member_slug = 'benjamin-henkle' WHERE member_slug = 'henkle';
UPDATE watchlist SET member_slug = 'benjamin-henkle' WHERE member_slug = 'henkle';
UPDATE comments SET author_id = 'benjamin-henkle' WHERE author_id = 'henkle';
DELETE FROM team_members WHERE id = 'henkle';

-- ─── macdonald → dave-macdonald ────────────────────────────────────────────
INSERT INTO team_members (id, name, role, credentials, slug, photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at)
  SELECT 'dave-macdonald', name, role, credentials, 'dave-macdonald', photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at
  FROM team_members WHERE id = 'macdonald';
UPDATE activity_log SET actor = 'dave-macdonald' WHERE actor = 'macdonald';
UPDATE action_items SET assignee = 'dave-macdonald' WHERE assignee = 'macdonald';
UPDATE action_items SET completed_by = 'dave-macdonald' WHERE completed_by = 'macdonald';
UPDATE action_items SET created_by = 'dave-macdonald' WHERE created_by = 'macdonald';
UPDATE agenda_items SET added_by = 'dave-macdonald' WHERE added_by = 'macdonald';
UPDATE ai_requests SET requested_by = 'dave-macdonald' WHERE requested_by = 'macdonald';
UPDATE commitments SET to_whom = 'dave-macdonald' WHERE to_whom = 'macdonald';
UPDATE contributions SET member_slug = 'dave-macdonald' WHERE member_slug = 'macdonald';
UPDATE hub_decisions SET decided_by = 'dave-macdonald' WHERE decided_by = 'macdonald';
UPDATE digest_comments SET author_slug = 'dave-macdonald' WHERE author_slug = 'macdonald';
UPDATE expertise_tags SET member_slug = 'dave-macdonald' WHERE member_slug = 'macdonald';
UPDATE file_attachments SET uploaded_by = 'dave-macdonald' WHERE uploaded_by = 'macdonald';
UPDATE grants SET pi = 'dave-macdonald' WHERE pi = 'macdonald';
UPDATE ideas SET submitted_by = 'dave-macdonald' WHERE submitted_by = 'macdonald';
UPDATE inbox SET author = 'dave-macdonald' WHERE author = 'macdonald';
UPDATE lab_answers SET author_slug = 'dave-macdonald' WHERE author_slug = 'macdonald';
UPDATE lab_questions SET asked_by = 'dave-macdonald' WHERE asked_by = 'macdonald';
UPDATE mentee_milestones SET mentee_slug = 'dave-macdonald' WHERE mentee_slug = 'macdonald';
UPDATE milestones SET future_note_author = 'dave-macdonald' WHERE future_note_author = 'macdonald';
UPDATE notifications SET recipient_slug = 'dave-macdonald' WHERE recipient_slug = 'macdonald';
UPDATE paper_project_links SET linked_by = 'dave-macdonald' WHERE linked_by = 'macdonald';
UPDATE project_dependencies SET created_by = 'dave-macdonald' WHERE created_by = 'macdonald';
UPDATE project_documents SET created_by = 'dave-macdonald' WHERE created_by = 'macdonald';
UPDATE project_updates SET author = 'dave-macdonald' WHERE author = 'macdonald';
UPDATE projects SET pi = 'dave-macdonald' WHERE pi = 'macdonald';
UPDATE reactions SET user_slug = 'dave-macdonald' WHERE user_slug = 'macdonald';
UPDATE research_digest SET saved_by = 'dave-macdonald' WHERE saved_by = 'macdonald';
UPDATE research_narratives SET created_by = 'dave-macdonald' WHERE created_by = 'macdonald';
UPDATE tasks SET assignee = 'dave-macdonald' WHERE assignee = 'macdonald';
UPDATE tasks SET assigned_by = 'dave-macdonald' WHERE assigned_by = 'macdonald';
UPDATE tasks SET completed_by = 'dave-macdonald' WHERE completed_by = 'macdonald';
UPDATE tasks SET acknowledged_by = 'dave-macdonald' WHERE acknowledged_by = 'macdonald';
UPDATE task_comments SET author_slug = 'dave-macdonald' WHERE author_slug = 'macdonald';
UPDATE task_files SET uploaded_by = 'dave-macdonald' WHERE uploaded_by = 'macdonald';
UPDATE task_handoffs SET from_slug = 'dave-macdonald' WHERE from_slug = 'macdonald';
UPDATE task_handoffs SET to_slug = 'dave-macdonald' WHERE to_slug = 'macdonald';
UPDATE task_subtasks SET completed_by = 'dave-macdonald' WHERE completed_by = 'macdonald';
UPDATE task_updates SET author_slug = 'dave-macdonald' WHERE author_slug = 'macdonald';
UPDATE trainee_milestones SET member_slug = 'dave-macdonald' WHERE member_slug = 'macdonald';
UPDATE watchlist SET member_slug = 'dave-macdonald' WHERE member_slug = 'macdonald';
UPDATE comments SET author_id = 'dave-macdonald' WHERE author_id = 'macdonald';
DELETE FROM team_members WHERE id = 'macdonald';

-- ─── trujeque → josh-trujeque ────────────────────────────────────────────
INSERT INTO team_members (id, name, role, credentials, slug, photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at)
  SELECT 'josh-trujeque', name, role, credentials, 'josh-trujeque', photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at
  FROM team_members WHERE id = 'trujeque';
UPDATE activity_log SET actor = 'josh-trujeque' WHERE actor = 'trujeque';
UPDATE action_items SET assignee = 'josh-trujeque' WHERE assignee = 'trujeque';
UPDATE action_items SET completed_by = 'josh-trujeque' WHERE completed_by = 'trujeque';
UPDATE action_items SET created_by = 'josh-trujeque' WHERE created_by = 'trujeque';
UPDATE agenda_items SET added_by = 'josh-trujeque' WHERE added_by = 'trujeque';
UPDATE ai_requests SET requested_by = 'josh-trujeque' WHERE requested_by = 'trujeque';
UPDATE commitments SET to_whom = 'josh-trujeque' WHERE to_whom = 'trujeque';
UPDATE contributions SET member_slug = 'josh-trujeque' WHERE member_slug = 'trujeque';
UPDATE hub_decisions SET decided_by = 'josh-trujeque' WHERE decided_by = 'trujeque';
UPDATE digest_comments SET author_slug = 'josh-trujeque' WHERE author_slug = 'trujeque';
UPDATE expertise_tags SET member_slug = 'josh-trujeque' WHERE member_slug = 'trujeque';
UPDATE file_attachments SET uploaded_by = 'josh-trujeque' WHERE uploaded_by = 'trujeque';
UPDATE grants SET pi = 'josh-trujeque' WHERE pi = 'trujeque';
UPDATE ideas SET submitted_by = 'josh-trujeque' WHERE submitted_by = 'trujeque';
UPDATE inbox SET author = 'josh-trujeque' WHERE author = 'trujeque';
UPDATE lab_answers SET author_slug = 'josh-trujeque' WHERE author_slug = 'trujeque';
UPDATE lab_questions SET asked_by = 'josh-trujeque' WHERE asked_by = 'trujeque';
UPDATE mentee_milestones SET mentee_slug = 'josh-trujeque' WHERE mentee_slug = 'trujeque';
UPDATE milestones SET future_note_author = 'josh-trujeque' WHERE future_note_author = 'trujeque';
UPDATE notifications SET recipient_slug = 'josh-trujeque' WHERE recipient_slug = 'trujeque';
UPDATE paper_project_links SET linked_by = 'josh-trujeque' WHERE linked_by = 'trujeque';
UPDATE project_dependencies SET created_by = 'josh-trujeque' WHERE created_by = 'trujeque';
UPDATE project_documents SET created_by = 'josh-trujeque' WHERE created_by = 'trujeque';
UPDATE project_updates SET author = 'josh-trujeque' WHERE author = 'trujeque';
UPDATE projects SET pi = 'josh-trujeque' WHERE pi = 'trujeque';
UPDATE reactions SET user_slug = 'josh-trujeque' WHERE user_slug = 'trujeque';
UPDATE research_digest SET saved_by = 'josh-trujeque' WHERE saved_by = 'trujeque';
UPDATE research_narratives SET created_by = 'josh-trujeque' WHERE created_by = 'trujeque';
UPDATE tasks SET assignee = 'josh-trujeque' WHERE assignee = 'trujeque';
UPDATE tasks SET assigned_by = 'josh-trujeque' WHERE assigned_by = 'trujeque';
UPDATE tasks SET completed_by = 'josh-trujeque' WHERE completed_by = 'trujeque';
UPDATE tasks SET acknowledged_by = 'josh-trujeque' WHERE acknowledged_by = 'trujeque';
UPDATE task_comments SET author_slug = 'josh-trujeque' WHERE author_slug = 'trujeque';
UPDATE task_files SET uploaded_by = 'josh-trujeque' WHERE uploaded_by = 'trujeque';
UPDATE task_handoffs SET from_slug = 'josh-trujeque' WHERE from_slug = 'trujeque';
UPDATE task_handoffs SET to_slug = 'josh-trujeque' WHERE to_slug = 'trujeque';
UPDATE task_subtasks SET completed_by = 'josh-trujeque' WHERE completed_by = 'trujeque';
UPDATE task_updates SET author_slug = 'josh-trujeque' WHERE author_slug = 'trujeque';
UPDATE trainee_milestones SET member_slug = 'josh-trujeque' WHERE member_slug = 'trujeque';
UPDATE watchlist SET member_slug = 'josh-trujeque' WHERE member_slug = 'trujeque';
UPDATE comments SET author_id = 'josh-trujeque' WHERE author_id = 'trujeque';
DELETE FROM team_members WHERE id = 'trujeque';

-- ─── pendleton → katie-pendleton ────────────────────────────────────────────
INSERT INTO team_members (id, name, role, credentials, slug, photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at)
  SELECT 'katie-pendleton', name, role, credentials, 'katie-pendleton', photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at
  FROM team_members WHERE id = 'pendleton';
UPDATE activity_log SET actor = 'katie-pendleton' WHERE actor = 'pendleton';
UPDATE action_items SET assignee = 'katie-pendleton' WHERE assignee = 'pendleton';
UPDATE action_items SET completed_by = 'katie-pendleton' WHERE completed_by = 'pendleton';
UPDATE action_items SET created_by = 'katie-pendleton' WHERE created_by = 'pendleton';
UPDATE agenda_items SET added_by = 'katie-pendleton' WHERE added_by = 'pendleton';
UPDATE ai_requests SET requested_by = 'katie-pendleton' WHERE requested_by = 'pendleton';
UPDATE commitments SET to_whom = 'katie-pendleton' WHERE to_whom = 'pendleton';
UPDATE contributions SET member_slug = 'katie-pendleton' WHERE member_slug = 'pendleton';
UPDATE hub_decisions SET decided_by = 'katie-pendleton' WHERE decided_by = 'pendleton';
UPDATE digest_comments SET author_slug = 'katie-pendleton' WHERE author_slug = 'pendleton';
UPDATE expertise_tags SET member_slug = 'katie-pendleton' WHERE member_slug = 'pendleton';
UPDATE file_attachments SET uploaded_by = 'katie-pendleton' WHERE uploaded_by = 'pendleton';
UPDATE grants SET pi = 'katie-pendleton' WHERE pi = 'pendleton';
UPDATE ideas SET submitted_by = 'katie-pendleton' WHERE submitted_by = 'pendleton';
UPDATE inbox SET author = 'katie-pendleton' WHERE author = 'pendleton';
UPDATE lab_answers SET author_slug = 'katie-pendleton' WHERE author_slug = 'pendleton';
UPDATE lab_questions SET asked_by = 'katie-pendleton' WHERE asked_by = 'pendleton';
UPDATE mentee_milestones SET mentee_slug = 'katie-pendleton' WHERE mentee_slug = 'pendleton';
UPDATE milestones SET future_note_author = 'katie-pendleton' WHERE future_note_author = 'pendleton';
UPDATE notifications SET recipient_slug = 'katie-pendleton' WHERE recipient_slug = 'pendleton';
UPDATE paper_project_links SET linked_by = 'katie-pendleton' WHERE linked_by = 'pendleton';
UPDATE project_dependencies SET created_by = 'katie-pendleton' WHERE created_by = 'pendleton';
UPDATE project_documents SET created_by = 'katie-pendleton' WHERE created_by = 'pendleton';
UPDATE project_updates SET author = 'katie-pendleton' WHERE author = 'pendleton';
UPDATE projects SET pi = 'katie-pendleton' WHERE pi = 'pendleton';
UPDATE reactions SET user_slug = 'katie-pendleton' WHERE user_slug = 'pendleton';
UPDATE research_digest SET saved_by = 'katie-pendleton' WHERE saved_by = 'pendleton';
UPDATE research_narratives SET created_by = 'katie-pendleton' WHERE created_by = 'pendleton';
UPDATE tasks SET assignee = 'katie-pendleton' WHERE assignee = 'pendleton';
UPDATE tasks SET assigned_by = 'katie-pendleton' WHERE assigned_by = 'pendleton';
UPDATE tasks SET completed_by = 'katie-pendleton' WHERE completed_by = 'pendleton';
UPDATE tasks SET acknowledged_by = 'katie-pendleton' WHERE acknowledged_by = 'pendleton';
UPDATE task_comments SET author_slug = 'katie-pendleton' WHERE author_slug = 'pendleton';
UPDATE task_files SET uploaded_by = 'katie-pendleton' WHERE uploaded_by = 'pendleton';
UPDATE task_handoffs SET from_slug = 'katie-pendleton' WHERE from_slug = 'pendleton';
UPDATE task_handoffs SET to_slug = 'katie-pendleton' WHERE to_slug = 'pendleton';
UPDATE task_subtasks SET completed_by = 'katie-pendleton' WHERE completed_by = 'pendleton';
UPDATE task_updates SET author_slug = 'katie-pendleton' WHERE author_slug = 'pendleton';
UPDATE trainee_milestones SET member_slug = 'katie-pendleton' WHERE member_slug = 'pendleton';
UPDATE watchlist SET member_slug = 'katie-pendleton' WHERE member_slug = 'pendleton';
UPDATE comments SET author_id = 'katie-pendleton' WHERE author_id = 'pendleton';
DELETE FROM team_members WHERE id = 'pendleton';

-- ─── kalinoski → michael-kalinoski ────────────────────────────────────────────
INSERT INTO team_members (id, name, role, credentials, slug, photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at)
  SELECT 'michael-kalinoski', name, role, credentials, 'michael-kalinoski', photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at
  FROM team_members WHERE id = 'kalinoski';
UPDATE activity_log SET actor = 'michael-kalinoski' WHERE actor = 'kalinoski';
UPDATE action_items SET assignee = 'michael-kalinoski' WHERE assignee = 'kalinoski';
UPDATE action_items SET completed_by = 'michael-kalinoski' WHERE completed_by = 'kalinoski';
UPDATE action_items SET created_by = 'michael-kalinoski' WHERE created_by = 'kalinoski';
UPDATE agenda_items SET added_by = 'michael-kalinoski' WHERE added_by = 'kalinoski';
UPDATE ai_requests SET requested_by = 'michael-kalinoski' WHERE requested_by = 'kalinoski';
UPDATE commitments SET to_whom = 'michael-kalinoski' WHERE to_whom = 'kalinoski';
UPDATE contributions SET member_slug = 'michael-kalinoski' WHERE member_slug = 'kalinoski';
UPDATE hub_decisions SET decided_by = 'michael-kalinoski' WHERE decided_by = 'kalinoski';
UPDATE digest_comments SET author_slug = 'michael-kalinoski' WHERE author_slug = 'kalinoski';
UPDATE expertise_tags SET member_slug = 'michael-kalinoski' WHERE member_slug = 'kalinoski';
UPDATE file_attachments SET uploaded_by = 'michael-kalinoski' WHERE uploaded_by = 'kalinoski';
UPDATE grants SET pi = 'michael-kalinoski' WHERE pi = 'kalinoski';
UPDATE ideas SET submitted_by = 'michael-kalinoski' WHERE submitted_by = 'kalinoski';
UPDATE inbox SET author = 'michael-kalinoski' WHERE author = 'kalinoski';
UPDATE lab_answers SET author_slug = 'michael-kalinoski' WHERE author_slug = 'kalinoski';
UPDATE lab_questions SET asked_by = 'michael-kalinoski' WHERE asked_by = 'kalinoski';
UPDATE mentee_milestones SET mentee_slug = 'michael-kalinoski' WHERE mentee_slug = 'kalinoski';
UPDATE milestones SET future_note_author = 'michael-kalinoski' WHERE future_note_author = 'kalinoski';
UPDATE notifications SET recipient_slug = 'michael-kalinoski' WHERE recipient_slug = 'kalinoski';
UPDATE paper_project_links SET linked_by = 'michael-kalinoski' WHERE linked_by = 'kalinoski';
UPDATE project_dependencies SET created_by = 'michael-kalinoski' WHERE created_by = 'kalinoski';
UPDATE project_documents SET created_by = 'michael-kalinoski' WHERE created_by = 'kalinoski';
UPDATE project_updates SET author = 'michael-kalinoski' WHERE author = 'kalinoski';
UPDATE projects SET pi = 'michael-kalinoski' WHERE pi = 'kalinoski';
UPDATE reactions SET user_slug = 'michael-kalinoski' WHERE user_slug = 'kalinoski';
UPDATE research_digest SET saved_by = 'michael-kalinoski' WHERE saved_by = 'kalinoski';
UPDATE research_narratives SET created_by = 'michael-kalinoski' WHERE created_by = 'kalinoski';
UPDATE tasks SET assignee = 'michael-kalinoski' WHERE assignee = 'kalinoski';
UPDATE tasks SET assigned_by = 'michael-kalinoski' WHERE assigned_by = 'kalinoski';
UPDATE tasks SET completed_by = 'michael-kalinoski' WHERE completed_by = 'kalinoski';
UPDATE tasks SET acknowledged_by = 'michael-kalinoski' WHERE acknowledged_by = 'kalinoski';
UPDATE task_comments SET author_slug = 'michael-kalinoski' WHERE author_slug = 'kalinoski';
UPDATE task_files SET uploaded_by = 'michael-kalinoski' WHERE uploaded_by = 'kalinoski';
UPDATE task_handoffs SET from_slug = 'michael-kalinoski' WHERE from_slug = 'kalinoski';
UPDATE task_handoffs SET to_slug = 'michael-kalinoski' WHERE to_slug = 'kalinoski';
UPDATE task_subtasks SET completed_by = 'michael-kalinoski' WHERE completed_by = 'kalinoski';
UPDATE task_updates SET author_slug = 'michael-kalinoski' WHERE author_slug = 'kalinoski';
UPDATE trainee_milestones SET member_slug = 'michael-kalinoski' WHERE member_slug = 'kalinoski';
UPDATE watchlist SET member_slug = 'michael-kalinoski' WHERE member_slug = 'kalinoski';
UPDATE comments SET author_id = 'michael-kalinoski' WHERE author_id = 'kalinoski';
DELETE FROM team_members WHERE id = 'kalinoski';

-- ─── wacker → dave-wacker ────────────────────────────────────────────
INSERT INTO team_members (id, name, role, credentials, slug, photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at)
  SELECT 'dave-wacker', name, role, credentials, 'dave-wacker', photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at
  FROM team_members WHERE id = 'wacker';
UPDATE activity_log SET actor = 'dave-wacker' WHERE actor = 'wacker';
UPDATE action_items SET assignee = 'dave-wacker' WHERE assignee = 'wacker';
UPDATE action_items SET completed_by = 'dave-wacker' WHERE completed_by = 'wacker';
UPDATE action_items SET created_by = 'dave-wacker' WHERE created_by = 'wacker';
UPDATE agenda_items SET added_by = 'dave-wacker' WHERE added_by = 'wacker';
UPDATE ai_requests SET requested_by = 'dave-wacker' WHERE requested_by = 'wacker';
UPDATE commitments SET to_whom = 'dave-wacker' WHERE to_whom = 'wacker';
UPDATE contributions SET member_slug = 'dave-wacker' WHERE member_slug = 'wacker';
UPDATE hub_decisions SET decided_by = 'dave-wacker' WHERE decided_by = 'wacker';
UPDATE digest_comments SET author_slug = 'dave-wacker' WHERE author_slug = 'wacker';
UPDATE expertise_tags SET member_slug = 'dave-wacker' WHERE member_slug = 'wacker';
UPDATE file_attachments SET uploaded_by = 'dave-wacker' WHERE uploaded_by = 'wacker';
UPDATE grants SET pi = 'dave-wacker' WHERE pi = 'wacker';
UPDATE ideas SET submitted_by = 'dave-wacker' WHERE submitted_by = 'wacker';
UPDATE inbox SET author = 'dave-wacker' WHERE author = 'wacker';
UPDATE lab_answers SET author_slug = 'dave-wacker' WHERE author_slug = 'wacker';
UPDATE lab_questions SET asked_by = 'dave-wacker' WHERE asked_by = 'wacker';
UPDATE mentee_milestones SET mentee_slug = 'dave-wacker' WHERE mentee_slug = 'wacker';
UPDATE milestones SET future_note_author = 'dave-wacker' WHERE future_note_author = 'wacker';
UPDATE notifications SET recipient_slug = 'dave-wacker' WHERE recipient_slug = 'wacker';
UPDATE paper_project_links SET linked_by = 'dave-wacker' WHERE linked_by = 'wacker';
UPDATE project_dependencies SET created_by = 'dave-wacker' WHERE created_by = 'wacker';
UPDATE project_documents SET created_by = 'dave-wacker' WHERE created_by = 'wacker';
UPDATE project_updates SET author = 'dave-wacker' WHERE author = 'wacker';
UPDATE projects SET pi = 'dave-wacker' WHERE pi = 'wacker';
UPDATE reactions SET user_slug = 'dave-wacker' WHERE user_slug = 'wacker';
UPDATE research_digest SET saved_by = 'dave-wacker' WHERE saved_by = 'wacker';
UPDATE research_narratives SET created_by = 'dave-wacker' WHERE created_by = 'wacker';
UPDATE tasks SET assignee = 'dave-wacker' WHERE assignee = 'wacker';
UPDATE tasks SET assigned_by = 'dave-wacker' WHERE assigned_by = 'wacker';
UPDATE tasks SET completed_by = 'dave-wacker' WHERE completed_by = 'wacker';
UPDATE tasks SET acknowledged_by = 'dave-wacker' WHERE acknowledged_by = 'wacker';
UPDATE task_comments SET author_slug = 'dave-wacker' WHERE author_slug = 'wacker';
UPDATE task_files SET uploaded_by = 'dave-wacker' WHERE uploaded_by = 'wacker';
UPDATE task_handoffs SET from_slug = 'dave-wacker' WHERE from_slug = 'wacker';
UPDATE task_handoffs SET to_slug = 'dave-wacker' WHERE to_slug = 'wacker';
UPDATE task_subtasks SET completed_by = 'dave-wacker' WHERE completed_by = 'wacker';
UPDATE task_updates SET author_slug = 'dave-wacker' WHERE author_slug = 'wacker';
UPDATE trainee_milestones SET member_slug = 'dave-wacker' WHERE member_slug = 'wacker';
UPDATE watchlist SET member_slug = 'dave-wacker' WHERE member_slug = 'wacker';
UPDATE comments SET author_id = 'dave-wacker' WHERE author_id = 'wacker';
DELETE FROM team_members WHERE id = 'wacker';

-- ─── arriaza → steven-arriaza ────────────────────────────────────────────
INSERT INTO team_members (id, name, role, credentials, slug, photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at)
  SELECT 'steven-arriaza', name, role, credentials, 'steven-arriaza', photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at
  FROM team_members WHERE id = 'arriaza';
UPDATE activity_log SET actor = 'steven-arriaza' WHERE actor = 'arriaza';
UPDATE action_items SET assignee = 'steven-arriaza' WHERE assignee = 'arriaza';
UPDATE action_items SET completed_by = 'steven-arriaza' WHERE completed_by = 'arriaza';
UPDATE action_items SET created_by = 'steven-arriaza' WHERE created_by = 'arriaza';
UPDATE agenda_items SET added_by = 'steven-arriaza' WHERE added_by = 'arriaza';
UPDATE ai_requests SET requested_by = 'steven-arriaza' WHERE requested_by = 'arriaza';
UPDATE commitments SET to_whom = 'steven-arriaza' WHERE to_whom = 'arriaza';
UPDATE contributions SET member_slug = 'steven-arriaza' WHERE member_slug = 'arriaza';
UPDATE hub_decisions SET decided_by = 'steven-arriaza' WHERE decided_by = 'arriaza';
UPDATE digest_comments SET author_slug = 'steven-arriaza' WHERE author_slug = 'arriaza';
UPDATE expertise_tags SET member_slug = 'steven-arriaza' WHERE member_slug = 'arriaza';
UPDATE file_attachments SET uploaded_by = 'steven-arriaza' WHERE uploaded_by = 'arriaza';
UPDATE grants SET pi = 'steven-arriaza' WHERE pi = 'arriaza';
UPDATE ideas SET submitted_by = 'steven-arriaza' WHERE submitted_by = 'arriaza';
UPDATE inbox SET author = 'steven-arriaza' WHERE author = 'arriaza';
UPDATE lab_answers SET author_slug = 'steven-arriaza' WHERE author_slug = 'arriaza';
UPDATE lab_questions SET asked_by = 'steven-arriaza' WHERE asked_by = 'arriaza';
UPDATE mentee_milestones SET mentee_slug = 'steven-arriaza' WHERE mentee_slug = 'arriaza';
UPDATE milestones SET future_note_author = 'steven-arriaza' WHERE future_note_author = 'arriaza';
UPDATE notifications SET recipient_slug = 'steven-arriaza' WHERE recipient_slug = 'arriaza';
UPDATE paper_project_links SET linked_by = 'steven-arriaza' WHERE linked_by = 'arriaza';
UPDATE project_dependencies SET created_by = 'steven-arriaza' WHERE created_by = 'arriaza';
UPDATE project_documents SET created_by = 'steven-arriaza' WHERE created_by = 'arriaza';
UPDATE project_updates SET author = 'steven-arriaza' WHERE author = 'arriaza';
UPDATE projects SET pi = 'steven-arriaza' WHERE pi = 'arriaza';
UPDATE reactions SET user_slug = 'steven-arriaza' WHERE user_slug = 'arriaza';
UPDATE research_digest SET saved_by = 'steven-arriaza' WHERE saved_by = 'arriaza';
UPDATE research_narratives SET created_by = 'steven-arriaza' WHERE created_by = 'arriaza';
UPDATE tasks SET assignee = 'steven-arriaza' WHERE assignee = 'arriaza';
UPDATE tasks SET assigned_by = 'steven-arriaza' WHERE assigned_by = 'arriaza';
UPDATE tasks SET completed_by = 'steven-arriaza' WHERE completed_by = 'arriaza';
UPDATE tasks SET acknowledged_by = 'steven-arriaza' WHERE acknowledged_by = 'arriaza';
UPDATE task_comments SET author_slug = 'steven-arriaza' WHERE author_slug = 'arriaza';
UPDATE task_files SET uploaded_by = 'steven-arriaza' WHERE uploaded_by = 'arriaza';
UPDATE task_handoffs SET from_slug = 'steven-arriaza' WHERE from_slug = 'arriaza';
UPDATE task_handoffs SET to_slug = 'steven-arriaza' WHERE to_slug = 'arriaza';
UPDATE task_subtasks SET completed_by = 'steven-arriaza' WHERE completed_by = 'arriaza';
UPDATE task_updates SET author_slug = 'steven-arriaza' WHERE author_slug = 'arriaza';
UPDATE trainee_milestones SET member_slug = 'steven-arriaza' WHERE member_slug = 'arriaza';
UPDATE watchlist SET member_slug = 'steven-arriaza' WHERE member_slug = 'arriaza';
UPDATE comments SET author_id = 'steven-arriaza' WHERE author_id = 'arriaza';
DELETE FROM team_members WHERE id = 'arriaza';

-- ─── bromley → emma-bromley ────────────────────────────────────────────
INSERT INTO team_members (id, name, role, credentials, slug, photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at)
  SELECT 'emma-bromley', name, role, credentials, 'emma-bromley', photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at
  FROM team_members WHERE id = 'bromley';
UPDATE activity_log SET actor = 'emma-bromley' WHERE actor = 'bromley';
UPDATE action_items SET assignee = 'emma-bromley' WHERE assignee = 'bromley';
UPDATE action_items SET completed_by = 'emma-bromley' WHERE completed_by = 'bromley';
UPDATE action_items SET created_by = 'emma-bromley' WHERE created_by = 'bromley';
UPDATE agenda_items SET added_by = 'emma-bromley' WHERE added_by = 'bromley';
UPDATE ai_requests SET requested_by = 'emma-bromley' WHERE requested_by = 'bromley';
UPDATE commitments SET to_whom = 'emma-bromley' WHERE to_whom = 'bromley';
UPDATE contributions SET member_slug = 'emma-bromley' WHERE member_slug = 'bromley';
UPDATE hub_decisions SET decided_by = 'emma-bromley' WHERE decided_by = 'bromley';
UPDATE digest_comments SET author_slug = 'emma-bromley' WHERE author_slug = 'bromley';
UPDATE expertise_tags SET member_slug = 'emma-bromley' WHERE member_slug = 'bromley';
UPDATE file_attachments SET uploaded_by = 'emma-bromley' WHERE uploaded_by = 'bromley';
UPDATE grants SET pi = 'emma-bromley' WHERE pi = 'bromley';
UPDATE ideas SET submitted_by = 'emma-bromley' WHERE submitted_by = 'bromley';
UPDATE inbox SET author = 'emma-bromley' WHERE author = 'bromley';
UPDATE lab_answers SET author_slug = 'emma-bromley' WHERE author_slug = 'bromley';
UPDATE lab_questions SET asked_by = 'emma-bromley' WHERE asked_by = 'bromley';
UPDATE mentee_milestones SET mentee_slug = 'emma-bromley' WHERE mentee_slug = 'bromley';
UPDATE milestones SET future_note_author = 'emma-bromley' WHERE future_note_author = 'bromley';
UPDATE notifications SET recipient_slug = 'emma-bromley' WHERE recipient_slug = 'bromley';
UPDATE paper_project_links SET linked_by = 'emma-bromley' WHERE linked_by = 'bromley';
UPDATE project_dependencies SET created_by = 'emma-bromley' WHERE created_by = 'bromley';
UPDATE project_documents SET created_by = 'emma-bromley' WHERE created_by = 'bromley';
UPDATE project_updates SET author = 'emma-bromley' WHERE author = 'bromley';
UPDATE projects SET pi = 'emma-bromley' WHERE pi = 'bromley';
UPDATE reactions SET user_slug = 'emma-bromley' WHERE user_slug = 'bromley';
UPDATE research_digest SET saved_by = 'emma-bromley' WHERE saved_by = 'bromley';
UPDATE research_narratives SET created_by = 'emma-bromley' WHERE created_by = 'bromley';
UPDATE tasks SET assignee = 'emma-bromley' WHERE assignee = 'bromley';
UPDATE tasks SET assigned_by = 'emma-bromley' WHERE assigned_by = 'bromley';
UPDATE tasks SET completed_by = 'emma-bromley' WHERE completed_by = 'bromley';
UPDATE tasks SET acknowledged_by = 'emma-bromley' WHERE acknowledged_by = 'bromley';
UPDATE task_comments SET author_slug = 'emma-bromley' WHERE author_slug = 'bromley';
UPDATE task_files SET uploaded_by = 'emma-bromley' WHERE uploaded_by = 'bromley';
UPDATE task_handoffs SET from_slug = 'emma-bromley' WHERE from_slug = 'bromley';
UPDATE task_handoffs SET to_slug = 'emma-bromley' WHERE to_slug = 'bromley';
UPDATE task_subtasks SET completed_by = 'emma-bromley' WHERE completed_by = 'bromley';
UPDATE task_updates SET author_slug = 'emma-bromley' WHERE author_slug = 'bromley';
UPDATE trainee_milestones SET member_slug = 'emma-bromley' WHERE member_slug = 'bromley';
UPDATE watchlist SET member_slug = 'emma-bromley' WHERE member_slug = 'bromley';
UPDATE comments SET author_id = 'emma-bromley' WHERE author_id = 'bromley';
DELETE FROM team_members WHERE id = 'bromley';

-- ─── eddington → casey-eddington ────────────────────────────────────────────
INSERT INTO team_members (id, name, role, credentials, slug, photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at)
  SELECT 'casey-eddington', name, role, credentials, 'casey-eddington', photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at
  FROM team_members WHERE id = 'eddington';
UPDATE activity_log SET actor = 'casey-eddington' WHERE actor = 'eddington';
UPDATE action_items SET assignee = 'casey-eddington' WHERE assignee = 'eddington';
UPDATE action_items SET completed_by = 'casey-eddington' WHERE completed_by = 'eddington';
UPDATE action_items SET created_by = 'casey-eddington' WHERE created_by = 'eddington';
UPDATE agenda_items SET added_by = 'casey-eddington' WHERE added_by = 'eddington';
UPDATE ai_requests SET requested_by = 'casey-eddington' WHERE requested_by = 'eddington';
UPDATE commitments SET to_whom = 'casey-eddington' WHERE to_whom = 'eddington';
UPDATE contributions SET member_slug = 'casey-eddington' WHERE member_slug = 'eddington';
UPDATE hub_decisions SET decided_by = 'casey-eddington' WHERE decided_by = 'eddington';
UPDATE digest_comments SET author_slug = 'casey-eddington' WHERE author_slug = 'eddington';
UPDATE expertise_tags SET member_slug = 'casey-eddington' WHERE member_slug = 'eddington';
UPDATE file_attachments SET uploaded_by = 'casey-eddington' WHERE uploaded_by = 'eddington';
UPDATE grants SET pi = 'casey-eddington' WHERE pi = 'eddington';
UPDATE ideas SET submitted_by = 'casey-eddington' WHERE submitted_by = 'eddington';
UPDATE inbox SET author = 'casey-eddington' WHERE author = 'eddington';
UPDATE lab_answers SET author_slug = 'casey-eddington' WHERE author_slug = 'eddington';
UPDATE lab_questions SET asked_by = 'casey-eddington' WHERE asked_by = 'eddington';
UPDATE mentee_milestones SET mentee_slug = 'casey-eddington' WHERE mentee_slug = 'eddington';
UPDATE milestones SET future_note_author = 'casey-eddington' WHERE future_note_author = 'eddington';
UPDATE notifications SET recipient_slug = 'casey-eddington' WHERE recipient_slug = 'eddington';
UPDATE paper_project_links SET linked_by = 'casey-eddington' WHERE linked_by = 'eddington';
UPDATE project_dependencies SET created_by = 'casey-eddington' WHERE created_by = 'eddington';
UPDATE project_documents SET created_by = 'casey-eddington' WHERE created_by = 'eddington';
UPDATE project_updates SET author = 'casey-eddington' WHERE author = 'eddington';
UPDATE projects SET pi = 'casey-eddington' WHERE pi = 'eddington';
UPDATE reactions SET user_slug = 'casey-eddington' WHERE user_slug = 'eddington';
UPDATE research_digest SET saved_by = 'casey-eddington' WHERE saved_by = 'eddington';
UPDATE research_narratives SET created_by = 'casey-eddington' WHERE created_by = 'eddington';
UPDATE tasks SET assignee = 'casey-eddington' WHERE assignee = 'eddington';
UPDATE tasks SET assigned_by = 'casey-eddington' WHERE assigned_by = 'eddington';
UPDATE tasks SET completed_by = 'casey-eddington' WHERE completed_by = 'eddington';
UPDATE tasks SET acknowledged_by = 'casey-eddington' WHERE acknowledged_by = 'eddington';
UPDATE task_comments SET author_slug = 'casey-eddington' WHERE author_slug = 'eddington';
UPDATE task_files SET uploaded_by = 'casey-eddington' WHERE uploaded_by = 'eddington';
UPDATE task_handoffs SET from_slug = 'casey-eddington' WHERE from_slug = 'eddington';
UPDATE task_handoffs SET to_slug = 'casey-eddington' WHERE to_slug = 'eddington';
UPDATE task_subtasks SET completed_by = 'casey-eddington' WHERE completed_by = 'eddington';
UPDATE task_updates SET author_slug = 'casey-eddington' WHERE author_slug = 'eddington';
UPDATE trainee_milestones SET member_slug = 'casey-eddington' WHERE member_slug = 'eddington';
UPDATE watchlist SET member_slug = 'casey-eddington' WHERE member_slug = 'eddington';
UPDATE comments SET author_id = 'casey-eddington' WHERE author_id = 'eddington';
DELETE FROM team_members WHERE id = 'eddington';

-- ─── shyu → dan-shyu ────────────────────────────────────────────
INSERT INTO team_members (id, name, role, credentials, slug, photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at)
  SELECT 'dan-shyu', name, role, credentials, 'dan-shyu', photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at
  FROM team_members WHERE id = 'shyu';
UPDATE activity_log SET actor = 'dan-shyu' WHERE actor = 'shyu';
UPDATE action_items SET assignee = 'dan-shyu' WHERE assignee = 'shyu';
UPDATE action_items SET completed_by = 'dan-shyu' WHERE completed_by = 'shyu';
UPDATE action_items SET created_by = 'dan-shyu' WHERE created_by = 'shyu';
UPDATE agenda_items SET added_by = 'dan-shyu' WHERE added_by = 'shyu';
UPDATE ai_requests SET requested_by = 'dan-shyu' WHERE requested_by = 'shyu';
UPDATE commitments SET to_whom = 'dan-shyu' WHERE to_whom = 'shyu';
UPDATE contributions SET member_slug = 'dan-shyu' WHERE member_slug = 'shyu';
UPDATE hub_decisions SET decided_by = 'dan-shyu' WHERE decided_by = 'shyu';
UPDATE digest_comments SET author_slug = 'dan-shyu' WHERE author_slug = 'shyu';
UPDATE expertise_tags SET member_slug = 'dan-shyu' WHERE member_slug = 'shyu';
UPDATE file_attachments SET uploaded_by = 'dan-shyu' WHERE uploaded_by = 'shyu';
UPDATE grants SET pi = 'dan-shyu' WHERE pi = 'shyu';
UPDATE ideas SET submitted_by = 'dan-shyu' WHERE submitted_by = 'shyu';
UPDATE inbox SET author = 'dan-shyu' WHERE author = 'shyu';
UPDATE lab_answers SET author_slug = 'dan-shyu' WHERE author_slug = 'shyu';
UPDATE lab_questions SET asked_by = 'dan-shyu' WHERE asked_by = 'shyu';
UPDATE mentee_milestones SET mentee_slug = 'dan-shyu' WHERE mentee_slug = 'shyu';
UPDATE milestones SET future_note_author = 'dan-shyu' WHERE future_note_author = 'shyu';
UPDATE notifications SET recipient_slug = 'dan-shyu' WHERE recipient_slug = 'shyu';
UPDATE paper_project_links SET linked_by = 'dan-shyu' WHERE linked_by = 'shyu';
UPDATE project_dependencies SET created_by = 'dan-shyu' WHERE created_by = 'shyu';
UPDATE project_documents SET created_by = 'dan-shyu' WHERE created_by = 'shyu';
UPDATE project_updates SET author = 'dan-shyu' WHERE author = 'shyu';
UPDATE projects SET pi = 'dan-shyu' WHERE pi = 'shyu';
UPDATE reactions SET user_slug = 'dan-shyu' WHERE user_slug = 'shyu';
UPDATE research_digest SET saved_by = 'dan-shyu' WHERE saved_by = 'shyu';
UPDATE research_narratives SET created_by = 'dan-shyu' WHERE created_by = 'shyu';
UPDATE tasks SET assignee = 'dan-shyu' WHERE assignee = 'shyu';
UPDATE tasks SET assigned_by = 'dan-shyu' WHERE assigned_by = 'shyu';
UPDATE tasks SET completed_by = 'dan-shyu' WHERE completed_by = 'shyu';
UPDATE tasks SET acknowledged_by = 'dan-shyu' WHERE acknowledged_by = 'shyu';
UPDATE task_comments SET author_slug = 'dan-shyu' WHERE author_slug = 'shyu';
UPDATE task_files SET uploaded_by = 'dan-shyu' WHERE uploaded_by = 'shyu';
UPDATE task_handoffs SET from_slug = 'dan-shyu' WHERE from_slug = 'shyu';
UPDATE task_handoffs SET to_slug = 'dan-shyu' WHERE to_slug = 'shyu';
UPDATE task_subtasks SET completed_by = 'dan-shyu' WHERE completed_by = 'shyu';
UPDATE task_updates SET author_slug = 'dan-shyu' WHERE author_slug = 'shyu';
UPDATE trainee_milestones SET member_slug = 'dan-shyu' WHERE member_slug = 'shyu';
UPDATE watchlist SET member_slug = 'dan-shyu' WHERE member_slug = 'shyu';
UPDATE comments SET author_id = 'dan-shyu' WHERE author_id = 'shyu';
DELETE FROM team_members WHERE id = 'shyu';

-- ─── fitzgerald → beret-fitzgerald ────────────────────────────────────────────
INSERT INTO team_members (id, name, role, credentials, slug, photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at)
  SELECT 'beret-fitzgerald', name, role, credentials, 'beret-fitzgerald', photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at
  FROM team_members WHERE id = 'fitzgerald';
UPDATE activity_log SET actor = 'beret-fitzgerald' WHERE actor = 'fitzgerald';
UPDATE action_items SET assignee = 'beret-fitzgerald' WHERE assignee = 'fitzgerald';
UPDATE action_items SET completed_by = 'beret-fitzgerald' WHERE completed_by = 'fitzgerald';
UPDATE action_items SET created_by = 'beret-fitzgerald' WHERE created_by = 'fitzgerald';
UPDATE agenda_items SET added_by = 'beret-fitzgerald' WHERE added_by = 'fitzgerald';
UPDATE ai_requests SET requested_by = 'beret-fitzgerald' WHERE requested_by = 'fitzgerald';
UPDATE commitments SET to_whom = 'beret-fitzgerald' WHERE to_whom = 'fitzgerald';
UPDATE contributions SET member_slug = 'beret-fitzgerald' WHERE member_slug = 'fitzgerald';
UPDATE hub_decisions SET decided_by = 'beret-fitzgerald' WHERE decided_by = 'fitzgerald';
UPDATE digest_comments SET author_slug = 'beret-fitzgerald' WHERE author_slug = 'fitzgerald';
UPDATE expertise_tags SET member_slug = 'beret-fitzgerald' WHERE member_slug = 'fitzgerald';
UPDATE file_attachments SET uploaded_by = 'beret-fitzgerald' WHERE uploaded_by = 'fitzgerald';
UPDATE grants SET pi = 'beret-fitzgerald' WHERE pi = 'fitzgerald';
UPDATE ideas SET submitted_by = 'beret-fitzgerald' WHERE submitted_by = 'fitzgerald';
UPDATE inbox SET author = 'beret-fitzgerald' WHERE author = 'fitzgerald';
UPDATE lab_answers SET author_slug = 'beret-fitzgerald' WHERE author_slug = 'fitzgerald';
UPDATE lab_questions SET asked_by = 'beret-fitzgerald' WHERE asked_by = 'fitzgerald';
UPDATE mentee_milestones SET mentee_slug = 'beret-fitzgerald' WHERE mentee_slug = 'fitzgerald';
UPDATE milestones SET future_note_author = 'beret-fitzgerald' WHERE future_note_author = 'fitzgerald';
UPDATE notifications SET recipient_slug = 'beret-fitzgerald' WHERE recipient_slug = 'fitzgerald';
UPDATE paper_project_links SET linked_by = 'beret-fitzgerald' WHERE linked_by = 'fitzgerald';
UPDATE project_dependencies SET created_by = 'beret-fitzgerald' WHERE created_by = 'fitzgerald';
UPDATE project_documents SET created_by = 'beret-fitzgerald' WHERE created_by = 'fitzgerald';
UPDATE project_updates SET author = 'beret-fitzgerald' WHERE author = 'fitzgerald';
UPDATE projects SET pi = 'beret-fitzgerald' WHERE pi = 'fitzgerald';
UPDATE reactions SET user_slug = 'beret-fitzgerald' WHERE user_slug = 'fitzgerald';
UPDATE research_digest SET saved_by = 'beret-fitzgerald' WHERE saved_by = 'fitzgerald';
UPDATE research_narratives SET created_by = 'beret-fitzgerald' WHERE created_by = 'fitzgerald';
UPDATE tasks SET assignee = 'beret-fitzgerald' WHERE assignee = 'fitzgerald';
UPDATE tasks SET assigned_by = 'beret-fitzgerald' WHERE assigned_by = 'fitzgerald';
UPDATE tasks SET completed_by = 'beret-fitzgerald' WHERE completed_by = 'fitzgerald';
UPDATE tasks SET acknowledged_by = 'beret-fitzgerald' WHERE acknowledged_by = 'fitzgerald';
UPDATE task_comments SET author_slug = 'beret-fitzgerald' WHERE author_slug = 'fitzgerald';
UPDATE task_files SET uploaded_by = 'beret-fitzgerald' WHERE uploaded_by = 'fitzgerald';
UPDATE task_handoffs SET from_slug = 'beret-fitzgerald' WHERE from_slug = 'fitzgerald';
UPDATE task_handoffs SET to_slug = 'beret-fitzgerald' WHERE to_slug = 'fitzgerald';
UPDATE task_subtasks SET completed_by = 'beret-fitzgerald' WHERE completed_by = 'fitzgerald';
UPDATE task_updates SET author_slug = 'beret-fitzgerald' WHERE author_slug = 'fitzgerald';
UPDATE trainee_milestones SET member_slug = 'beret-fitzgerald' WHERE member_slug = 'fitzgerald';
UPDATE watchlist SET member_slug = 'beret-fitzgerald' WHERE member_slug = 'fitzgerald';
UPDATE comments SET author_id = 'beret-fitzgerald' WHERE author_id = 'fitzgerald';
DELETE FROM team_members WHERE id = 'fitzgerald';

-- ─── collins → claire-collins ────────────────────────────────────────────
INSERT INTO team_members (id, name, role, credentials, slug, photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at)
  SELECT 'claire-collins', name, role, credentials, 'claire-collins', photo_url, bio, scholar_id, author_name, title, department, member_type, email, full_name, preferred_name, created_at
  FROM team_members WHERE id = 'collins';
UPDATE activity_log SET actor = 'claire-collins' WHERE actor = 'collins';
UPDATE action_items SET assignee = 'claire-collins' WHERE assignee = 'collins';
UPDATE action_items SET completed_by = 'claire-collins' WHERE completed_by = 'collins';
UPDATE action_items SET created_by = 'claire-collins' WHERE created_by = 'collins';
UPDATE agenda_items SET added_by = 'claire-collins' WHERE added_by = 'collins';
UPDATE ai_requests SET requested_by = 'claire-collins' WHERE requested_by = 'collins';
UPDATE commitments SET to_whom = 'claire-collins' WHERE to_whom = 'collins';
UPDATE contributions SET member_slug = 'claire-collins' WHERE member_slug = 'collins';
UPDATE hub_decisions SET decided_by = 'claire-collins' WHERE decided_by = 'collins';
UPDATE digest_comments SET author_slug = 'claire-collins' WHERE author_slug = 'collins';
UPDATE expertise_tags SET member_slug = 'claire-collins' WHERE member_slug = 'collins';
UPDATE file_attachments SET uploaded_by = 'claire-collins' WHERE uploaded_by = 'collins';
UPDATE grants SET pi = 'claire-collins' WHERE pi = 'collins';
UPDATE ideas SET submitted_by = 'claire-collins' WHERE submitted_by = 'collins';
UPDATE inbox SET author = 'claire-collins' WHERE author = 'collins';
UPDATE lab_answers SET author_slug = 'claire-collins' WHERE author_slug = 'collins';
UPDATE lab_questions SET asked_by = 'claire-collins' WHERE asked_by = 'collins';
UPDATE mentee_milestones SET mentee_slug = 'claire-collins' WHERE mentee_slug = 'collins';
UPDATE milestones SET future_note_author = 'claire-collins' WHERE future_note_author = 'collins';
UPDATE notifications SET recipient_slug = 'claire-collins' WHERE recipient_slug = 'collins';
UPDATE paper_project_links SET linked_by = 'claire-collins' WHERE linked_by = 'collins';
UPDATE project_dependencies SET created_by = 'claire-collins' WHERE created_by = 'collins';
UPDATE project_documents SET created_by = 'claire-collins' WHERE created_by = 'collins';
UPDATE project_updates SET author = 'claire-collins' WHERE author = 'collins';
UPDATE projects SET pi = 'claire-collins' WHERE pi = 'collins';
UPDATE reactions SET user_slug = 'claire-collins' WHERE user_slug = 'collins';
UPDATE research_digest SET saved_by = 'claire-collins' WHERE saved_by = 'collins';
UPDATE research_narratives SET created_by = 'claire-collins' WHERE created_by = 'collins';
UPDATE tasks SET assignee = 'claire-collins' WHERE assignee = 'collins';
UPDATE tasks SET assigned_by = 'claire-collins' WHERE assigned_by = 'collins';
UPDATE tasks SET completed_by = 'claire-collins' WHERE completed_by = 'collins';
UPDATE tasks SET acknowledged_by = 'claire-collins' WHERE acknowledged_by = 'collins';
UPDATE task_comments SET author_slug = 'claire-collins' WHERE author_slug = 'collins';
UPDATE task_files SET uploaded_by = 'claire-collins' WHERE uploaded_by = 'collins';
UPDATE task_handoffs SET from_slug = 'claire-collins' WHERE from_slug = 'collins';
UPDATE task_handoffs SET to_slug = 'claire-collins' WHERE to_slug = 'collins';
UPDATE task_subtasks SET completed_by = 'claire-collins' WHERE completed_by = 'collins';
UPDATE task_updates SET author_slug = 'claire-collins' WHERE author_slug = 'collins';
UPDATE trainee_milestones SET member_slug = 'claire-collins' WHERE member_slug = 'collins';
UPDATE watchlist SET member_slug = 'claire-collins' WHERE member_slug = 'collins';
UPDATE comments SET author_id = 'claire-collins' WHERE author_id = 'collins';
DELETE FROM team_members WHERE id = 'collins';

-- Optional: fold email-prefix-derived assignee slugs into canonical Nick.
UPDATE tasks SET assignee = 'nick-ingraham' WHERE assignee IN ('ningraha', 'ingra107');
