/**
 * Seed script for MN-CCORE Lab D1 database.
 *
 * Reads from src/data/*.ts and generates a SQL file with INSERT statements
 * that can be executed with: wrangler d1 execute mnccore-lab --file=scripts/seed.sql
 *
 * Usage: npx tsx scripts/seed-d1.ts
 */

import { publications } from '../src/data/publications';
import { projects } from '../src/data/projects';
import { directors, seniorMentors, facultyCollaborators, researchTeam } from '../src/data/team';
import { grants } from '../src/data/grants';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as crypto from 'node:crypto';

function esc(value: string | null | undefined): string {
  if (value == null) return 'NULL';
  return `'${value.replace(/'/g, "''")}'`;
}

function jsonOrNull(value: unknown): string {
  if (value == null) return 'NULL';
  if (Array.isArray(value) && value.length === 0) return 'NULL';
  return esc(JSON.stringify(value));
}

function numOrNull(value: number | boolean | null | undefined): string {
  if (value == null) return 'NULL';
  if (typeof value === 'boolean') return value ? '1' : '0';
  return String(value);
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

function uid(): string {
  return crypto.randomUUID();
}

const lines: string[] = [];

lines.push('-- MN-CCORE Lab Hub — Seed Data');
lines.push('-- Generated by scripts/seed-d1.ts');
lines.push(`-- Date: ${new Date().toISOString()}`);
lines.push('');
lines.push('-- Clear existing data');
lines.push('DELETE FROM comments;');
lines.push('DELETE FROM activity_log;');
lines.push('DELETE FROM milestones;');
lines.push('DELETE FROM grants;');
lines.push('DELETE FROM projects;');
lines.push('DELETE FROM publications;');
lines.push('DELETE FROM team_members;');
lines.push('');

// ── Team Members ──────────────────────────────────────────────────────────────

lines.push('-- Team Members');

// Directors
for (const d of directors) {
  lines.push(
    `INSERT INTO team_members (id, name, role, credentials, slug, photo_url, bio, scholar_id, author_name, title, department, member_type) VALUES (${esc(d.slug)}, ${esc(d.name)}, ${esc(d.role)}, ${esc(d.credentials)}, ${esc(d.slug)}, ${esc(d.photoUrl)}, ${esc(d.bio)}, ${esc(d.scholarId)}, NULL, ${esc(d.title)}, NULL, 'director');`
  );
}

// Senior Mentors
for (const m of seniorMentors) {
  lines.push(
    `INSERT INTO team_members (id, name, role, credentials, slug, photo_url, bio, scholar_id, author_name, title, department, member_type) VALUES (${esc(m.slug || slugify(m.name))}, ${esc(m.name)}, ${esc(m.role)}, ${esc(m.credentials)}, ${esc(m.slug)}, ${esc(m.photoUrl)}, ${esc(m.bio)}, ${esc(m.scholarId)}, ${esc(m.authorName)}, NULL, NULL, 'senior_mentor');`
  );
}

// Faculty Collaborators
for (const f of facultyCollaborators) {
  lines.push(
    `INSERT INTO team_members (id, name, role, credentials, slug, photo_url, bio, scholar_id, author_name, title, department, member_type) VALUES (${esc(f.slug || slugify(f.name))}, ${esc(f.name)}, ${esc(f.role)}, ${esc(f.credentials)}, ${esc(f.slug)}, ${esc(f.photoUrl)}, ${esc(f.bio)}, ${esc(f.scholarId)}, ${esc(f.authorName)}, NULL, NULL, 'faculty');`
  );
}

// Research Team
for (const r of researchTeam) {
  lines.push(
    `INSERT INTO team_members (id, name, role, credentials, slug, photo_url, bio, scholar_id, author_name, title, department, member_type) VALUES (${esc(r.slug || slugify(r.name))}, ${esc(r.name)}, ${esc(r.role)}, ${esc(r.credentials)}, ${esc(r.slug)}, ${esc(r.photoUrl)}, ${esc(r.bio)}, ${esc(r.scholarId)}, ${esc(r.authorName)}, NULL, NULL, 'research_team');`
  );
}

lines.push('');

// ── Publications ──────────────────────────────────────────────────────────────

lines.push('-- Publications');

for (const p of publications) {
  lines.push(
    `INSERT INTO publications (id, title, authors, journal, year, status, doi, pubmed, abstract, topics, featured, author_slugs) VALUES (${esc(p.id)}, ${esc(p.title)}, ${esc(p.authors)}, ${esc(p.journal)}, ${numOrNull(p.year)}, ${esc(p.status)}, ${esc(p.doi)}, ${esc(p.pubmed)}, ${esc(p.abstract)}, ${jsonOrNull(p.topics)}, ${numOrNull(p.featured ? 1 : 0)}, ${jsonOrNull(p.authorSlugs)});`
  );
}

lines.push('');

// ── Projects ──────────────────────────────────────────────────────────────────

lines.push('-- Projects');

for (const p of projects) {
  const id = p.slug || slugify(p.title);
  lines.push(
    `INSERT INTO projects (id, title, status, description, category, pi, slug) VALUES (${esc(id)}, ${esc(p.title)}, ${esc(p.status)}, ${esc(p.description)}, ${esc(p.category)}, ${esc(p.pi)}, ${esc(p.slug)});`
  );
}

lines.push('');

// ── Grants ────────────────────────────────────────────────────────────────────

lines.push('-- Grants');

for (const g of grants) {
  const id = slugify(`${g.mechanism}-${g.title}`);
  lines.push(
    `INSERT INTO grants (id, mechanism, title, agency, pi, proposed) VALUES (${esc(id)}, ${esc(g.mechanism)}, ${esc(g.title)}, ${esc(g.agency)}, ${esc(g.pi)}, ${numOrNull(g.proposed ? 1 : 0)});`
  );
}

lines.push('');

// ── Write output ──────────────────────────────────────────────────────────────

const outPath = path.join(import.meta.dirname, 'seed.sql');
fs.writeFileSync(outPath, lines.join('\n'), 'utf-8');

const pubCount = publications.length;
const projectCount = projects.length;
const teamCount = directors.length + seniorMentors.length + facultyCollaborators.length + researchTeam.length;
const grantCount = grants.length;

console.log(`Seed file written to ${outPath}`);
console.log(`  ${teamCount} team members (${directors.length} directors, ${seniorMentors.length} senior mentors, ${facultyCollaborators.length} faculty, ${researchTeam.length} research team)`);
console.log(`  ${pubCount} publications`);
console.log(`  ${projectCount} projects`);
console.log(`  ${grantCount} grants`);
console.log('');
console.log('To apply:');
console.log('  wrangler d1 execute mnccore-lab --file=scripts/seed.sql');
console.log('  wrangler d1 execute mnccore-lab --file=scripts/seed.sql --remote  (for production)');
