// Codex test #3 — hash-vector cross-language contract (Hub TS side).
//
// Loads the LOCAL committed copy of the shared vector file
// (./hash_vectors.json — generated byte-identical to PB's
// tests/fixtures/hash_vectors.json by scripts/db/gen_hash_vectors.py) and
// asserts hashTouched returns the baked-in expected_hash for each vector.
// Companion Python test at
// Peripheral-Brain/tests/db/test_a3_hash_contract.py runs the same vectors
// through canonical_json_hash. Both must agree byte-for-byte.
//
// WHY the local copy (backlog #730): the vector file used to live ONLY in PB
// and this test reached into an adjacent PB checkout at test time — absent in
// CI, so `describe.skipIf(vectors.length === 0)` SKIPPED the entire contract
// and protocol drift passed CI green. Now each repo carries its OWN committed
// copy, so the contract ALWAYS runs (drift FAILS, never skips). One generator
// (PB scripts/db/gen_hash_vectors.py) writes both copies byte-identical, so
// hand-divergence is not part of the normal workflow; the recompute below is
// the always-on producer-drift + staleness guard. (No cross-repo byte-compare:
// the two repos commit asynchronously, so there is always a window where one
// committed copy is ahead of the other; a blocking assertion on their equality
// would deadlock. Cross-repo consistency is guaranteed by the single generator
// plus each side's local recompute.)
//
// The hashTouched function takes (row, fields[]) — for these vectors the input
// dict IS the row, and we pass Object.keys() as fields. That mirrors how
// hashTouched is invoked from BrainDB writers.
import { describe, it, expect } from 'vitest'
import * as fs from 'node:fs'
import * as path from 'node:path'
import { hashTouched } from './mutations'

interface Vector {
  name: string
  input: Record<string, unknown>
  expected_hash: string
}

interface VectorFile {
  contract_version: number
  vectors: Vector[]
}

// Strip the leading slash Windows file URLs carry (/C:/... -> C:/...).
const HERE = path
  .dirname(new URL(import.meta.url).pathname)
  .replace(/^\/+([A-Za-z]:)/, '$1')
const LOCAL_VECTOR_FILE = path.resolve(HERE, 'hash_vectors.json')

// Committed in THIS repo — always present, so the contract runs in CI too. A
// missing file is a real repo breakage and MUST fail loud (not skip).
const local = JSON.parse(
  fs.readFileSync(LOCAL_VECTOR_FILE, 'utf-8'),
) as VectorFile

describe('hashTouched — cross-language contract with Python canonical_json_hash', () => {
  it('vector file carries a contract_version stamp and vectors', () => {
    expect(typeof local.contract_version).toBe('number')
    expect(local.vectors.length).toBeGreaterThan(0)
  })

  for (const v of local.vectors) {
    it(`matches Python hash for vector "${v.name}"`, async () => {
      const fields = Object.keys(v.input)
      const actual = await hashTouched(v.input, fields)
      expect(actual).toBe(v.expected_hash)
    })
  }

  it('reordered keys produce the same hash', async () => {
    const a = await hashTouched({ a: 1, b: 'hello' }, ['a', 'b'])
    const b = await hashTouched({ b: 'hello', a: 1 }, ['a', 'b'])
    expect(a).toBe(b)
  })

  it('field order in fields[] does not affect the hash', async () => {
    const a = await hashTouched({ a: 1, b: 2 }, ['a', 'b'])
    const b = await hashTouched({ a: 1, b: 2 }, ['b', 'a'])
    expect(a).toBe(b)
  })
})
