/**
 * iconMapParity.test.ts — cross-repo drift gate between PB_LINK_ICONS
 * (generated by gen_links.py from link_contract.py) and the Hub rendering
 * layer (linkIcon.ts + index.css).
 *
 * Three assertions per link type:
 *   (a) LUCIDE_REGISTRY has the named component — no silent Globe fallback.
 *   (b) iconForType(type).color follows the expected CSS variable convention.
 *   (c) The light-mode CSS token value in index.css matches
 *       PB_LINK_ICONS[type].color (hex-case-insensitive, uppercase normalized).
 *
 * Run: npx vitest run --config vitest.config.lib.ts
 *
 * If (a) fails: add the new Lucide import + LUCIDE_REGISTRY entry in linkIcon.ts.
 * If (b) fails: cssTokenForType() produced an unexpected string.
 * If (c) fails: re-sync index.css --link-* hex values with link_contract.py
 *               or regenerate via gen_links.py.
 */

import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { PB_LINK_ICONS } from '../pbLinkIcons.generated'
import { iconForType, cssTokenForType } from '../linkIcon'

// ── CSS token light-mode hex map ─────────────────────────────
// Parsed from src/index.css :root block.  We take the FIRST occurrence of
// each --link-* token so that .dark overrides don't pollute the light values.
function parseCssLightTokens(): Record<string, string> {
  const cssPath = resolve(__dirname, '../../index.css')
  const css = readFileSync(cssPath, 'utf-8')
  const result: Record<string, string> = {}
  // Match every --link-<name>: #RRGGBB; inside any block (first-wins = :root
  // since :root appears before .dark in the file).
  const re = /(--link-[\w-]+)\s*:\s*(#[0-9A-Fa-f]{6})/g
  let m: RegExpExecArray | null
  while ((m = re.exec(css)) !== null) {
    const [, token, hex] = m
    if (!(token in result)) {
      result[token] = hex.toUpperCase()
    }
  }
  return result
}

const CSS_LIGHT_TOKENS = parseCssLightTokens()

// ── Tests ────────────────────────────────────────────────────

describe('PB_LINK_ICONS ↔ ICON_MAP parity', () => {
  const types = Object.keys(PB_LINK_ICONS)

  it('covers all 15 link types from link_contract.py', () => {
    expect(types.length).toBe(15)
  })

  for (const type of types) {
    const spec = PB_LINK_ICONS[type]

    it(`[${type}] LUCIDE_REGISTRY has '${spec.lucide}' (no silent Globe fallback)`, () => {
      const { Icon } = iconForType(type)
      // If LUCIDE_REGISTRY is missing the entry, linkIcon.ts falls back to Globe.
      // Globe.displayName is 'Globe'; spec.lucide for the failing type won't be Globe.
      // Exception: 'web' legitimately maps to Globe.
      if (type === 'web') {
        expect(Icon.displayName).toBe('Globe')
      } else {
        expect(Icon.displayName).toBe(spec.lucide)
      }
    })

    it(`[${type}] iconForType color is var(--link-${type.replace(/_/g, '-')})`, () => {
      const { color } = iconForType(type)
      const expectedToken = cssTokenForType(type)
      expect(color).toBe(`var(${expectedToken})`)
    })

    it(`[${type}] index.css light-mode token matches PB_LINK_ICONS color`, () => {
      const token = cssTokenForType(type)
      const cssHex = CSS_LIGHT_TOKENS[token]
      expect(cssHex, `CSS token ${token} not found in index.css :root`).toBeDefined()
      // Normalize both to uppercase for comparison.
      expect(cssHex).toBe(spec.color.toUpperCase())
    })
  }
})
