/**
 * linkIcon.ts unit tests (vitest, node environment via vitest.config.lib.ts).
 *
 * Covers:
 *   1. iconForType() returns correct Icon + color for known types.
 *   2. iconForType() falls back to 'web' for unknown/null/undefined.
 *   3. ICONS_HASH === PB contract hash (cross-repo drift gate).
 *
 * Run: npx vitest run --config vitest.config.lib.ts
 */

import { describe, it, expect } from 'vitest'
import { iconForType, ICONS_HASH } from '../linkIcon'
import { PencilLine, Globe } from 'lucide-react'

// PB contract hash — generated by gen_links.py and embedded in
// pbLinkIcons.generated.ts. If this assertion fails, the Hub icon map has
// drifted from the PB link_contract.py source of truth.
// Regenerate: cd ~/Peripheral-Brain && python -X utf8 scripts/links/gen_links.py
const PB_CONTRACT_HASH = '5403258cb2ddc522864425d90397b9f8994d95516e3830203b2ce769c43add4d'

describe('iconForType', () => {
  it('returns PencilLine for gmail_draft with Gmail red token', () => {
    const { Icon, color } = iconForType('gmail_draft')
    expect(Icon).toBe(PencilLine)
    expect(color).toBe('var(--link-gmail-draft)')
  })

  it('returns Globe for unknown type (fallback to web)', () => {
    const { Icon, color } = iconForType('???')
    expect(Icon).toBe(Globe)
    expect(color).toBe('var(--link-web)')
  })

  it('returns Globe for null (fallback to web)', () => {
    const { Icon } = iconForType(null)
    expect(Icon).toBe(Globe)
  })

  it('returns Globe for undefined (fallback to web)', () => {
    const { Icon } = iconForType(undefined)
    expect(Icon).toBe(Globe)
  })

  it('returns correct Icon for all 15 known types', () => {
    const types = [
      'google_doc', 'google_sheet', 'google_slide', 'google_form',
      'box_folder', 'github_repo', 'github_issue', 'github_tree',
      'gmail_thread', 'gmail_draft', 'obsidian_note',
      'local_folder', 'local_file', 'script', 'web',
    ]
    for (const t of types) {
      const spec = iconForType(t)
      expect(spec.Icon, `Icon for ${t} should be defined`).toBeDefined()
      expect(spec.color, `color for ${t} should be a CSS var`).toMatch(/^var\(--link-/)
    }
  })
})

describe('ICONS_HASH cross-repo drift gate', () => {
  it('matches the PB contract hash (pbLinkIcons.generated.ts)', () => {
    expect(ICONS_HASH).toBe(PB_CONTRACT_HASH)
  })
})
