import type { Publication } from './types'

/**
 * AUTO-GENERATED by scripts/fetch-publications.ts — do NOT hand-edit. (#357)
 * Regenerate with: npm run fetch:publications
 * ORCID primary / Google Scholar fenced fallback; build-time only.
 * These entries only fill gaps — mergePublications() keeps curated pubs
 * authoritative. Review before committing.
 */
export const generatedPublications: Publication[] = []
